using Microsoft.CodeAnalysis;
using Xunit;

namespace Expo.ModulesCore.Generator.Tests;

public sealed class ExpoModulesGeneratorTests
{
  [Fact]
  public void GeneratorEmitsDeterministicProviderForAssembly()
  {
    var result = GeneratorTestHost.Run(
        """
        using Expo.ModulesCore;

        namespace Expo.TestModules;

        [ExpoModule]
        public sealed partial class MathModule
        {
        }
        """
    );

    Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    var generatedSource = Assert.Single(result.GeneratedSources);
    Assert.EndsWith(".g.cs", generatedSource.HintName);
    var source = generatedSource.Text;
    Assert.Contains("// <auto-generated", source);
    Assert.Contains("public static class ExpoModulesProvider_Expo_TestModules", source);
    Assert.Contains(
        "public static void Register(global::Expo.ModulesCore.DotnetRuntimeContext context)",
        source
    );
    Assert.Contains(
        "public static void Register(global::Expo.ModulesCore.DotnetRuntimeContext context, global::Expo.JSI.JavaScriptObject modules)",
        source
    );
    Assert.DoesNotContain("public static void Register(global::Expo.JSI.JavaScriptRuntime runtime", source);
    Assert.Contains("global::System.ArgumentNullException.ThrowIfNull(context);", source);
    Assert.Contains("using var modules = context.GetOrCreateDotnetModulesObject();", source);
    Assert.Contains("Register(context, modules);", source);
    Assert.Contains("global::System.ArgumentNullException.ThrowIfNull(modules);", source);
    Assert.Contains("ModuleRegistry.DefineModule(context.Runtime, modules, \"Math\")", source);
    Assert.Contains("context.GetOrCreateModule(\"Math\", static () => new global::Expo.TestModules.MathModule())", source);
  }

  [Fact]
  public void GeneratorEmitsDefaultAndExplicitFunctionNames()
  {
    var result = GeneratorTestHost.Run(
        """
        using Expo.ModulesCore;

        namespace Expo.TestModules;

        [ExpoModule("Math")]
        public sealed partial class InternalMathModule
        {
          [JS]
          public double Add(double a, double b) => a + b;

          [JS("addOne")]
          public double Increment(double value) => value + 1.0;
        }
        """
    );

    Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    var source = Assert.Single(result.GeneratedSources).Text;
    Assert.Contains("ModuleRegistry.DefineModule(context.Runtime, modules, \"Math\")", source);
    Assert.Contains("context.GetOrCreateModule(\"Math\", static () => new global::Expo.TestModules.InternalMathModule())", source);
    Assert.Contains("GeneratedFunction.DefineSync(", source);
    Assert.Contains("module_Math", source);
    Assert.Contains("\"Add\"", source);
    Assert.Contains("\"addOne\"", source);
    Assert.Contains("module.Add(a, b)", source);
    Assert.Contains("module.Increment(value)", source);
  }

  [Fact]
  public void GeneratorReportsUnsupportedParameterType()
  {
    var result = GeneratorTestHost.Run(
        """
        using Expo.ModulesCore;

        namespace Expo.TestModules;

        [ExpoModule]
        public sealed partial class BadModule
        {
          [JS]
          public double Bad(decimal value) => 0.0;
        }
        """
    );

    var diagnostic = Assert.Single(result.Diagnostics, item => item.Id == "EXPOJSI001");
    Assert.Contains("value", diagnostic.GetMessage());
    Assert.Contains("System.Decimal", diagnostic.GetMessage());
  }

  [Fact]
  public void GeneratorReportsUnsupportedReturnType()
  {
    var result = GeneratorTestHost.Run(
        """
        using Expo.ModulesCore;

        namespace Expo.TestModules;

        [ExpoModule]
        public sealed partial class BadModule
        {
          [JS]
          public decimal Bad(double value) => 0m;
        }
        """
    );

    var diagnostic = Assert.Single(result.Diagnostics, item => item.Id == "EXPOJSI002");
    Assert.Contains("Bad", diagnostic.GetMessage());
    Assert.Contains("System.Decimal", diagnostic.GetMessage());
  }

  [Fact]
  public void GeneratorReportsStaticJSMethod()
  {
    var result = GeneratorTestHost.Run(
        """
        using Expo.ModulesCore;

        namespace Expo.TestModules;

        [ExpoModule]
        public sealed partial class BadModule
        {
          [JS]
          public static double Bad() => 1.0;
        }
        """
    );

    var diagnostic = Assert.Single(result.Diagnostics, item => item.Id == "EXPOJSI004");
    Assert.Contains("Bad", diagnostic.GetMessage());
    Assert.Contains("static", diagnostic.GetMessage());
  }

  [Fact]
  public void GeneratorReportsGenericJSMethod()
  {
    var result = GeneratorTestHost.Run(
        """
        using Expo.ModulesCore;

        namespace Expo.TestModules;

        [ExpoModule]
        public sealed partial class BadModule
        {
          [JS]
          public T Bad<T>(T value) => value;
        }
        """
    );

    var diagnostic = Assert.Single(result.Diagnostics, item => item.Id == "EXPOJSI004");
    Assert.Contains("Bad", diagnostic.GetMessage());
    Assert.Contains("generic", diagnostic.GetMessage());
  }

  [Fact]
  public void GeneratorReportsDuplicateJavaScriptFunctionName()
  {
    var result = GeneratorTestHost.Run(
        """
        using Expo.ModulesCore;

        namespace Expo.TestModules;

        [ExpoModule("Math")]
        public sealed partial class MathModule
        {
          [JS("same")]
          public double Add(double value) => value + 1.0;

          [JS("same")]
          public double Increment(double value) => value + 2.0;
        }
        """
    );

    var diagnostic = Assert.Single(result.Diagnostics, item => item.Id == "EXPOJSI005");
    Assert.Contains("Math", diagnostic.GetMessage());
    Assert.Contains("same", diagnostic.GetMessage());
  }

  [Fact]
  public void GeneratorReportsUnsupportedModuleConstructor()
  {
    var result = GeneratorTestHost.Run(
        """
        using Expo.ModulesCore;

        namespace Expo.TestModules;

        [ExpoModule]
        public sealed partial class BadModule
        {
          public BadModule(double value) {}

          [JS]
          public double Value() => 1.0;
        }
        """
    );

    var diagnostic = Assert.Single(result.Diagnostics, item => item.Id == "EXPOJSI003");
    Assert.Contains("Bad", diagnostic.GetMessage());
    Assert.DoesNotContain("new global::Expo.TestModules.BadModule()", string.Join("\n", result.GeneratedSources.Select(source => source.Text)));
  }

  [Fact]
  public void GeneratorReportsDuplicateModuleName()
  {
    var result = GeneratorTestHost.Run(
        """
        using Expo.ModulesCore;

        namespace Expo.TestModules;

        [ExpoModule("Math")]
        public sealed partial class FirstModule
        {
          [JS]
          public double Add(double value) => value + 1.0;
        }

        [ExpoModule("Math")]
        public sealed partial class SecondModule
        {
          [JS]
          public double Increment(double value) => value + 2.0;
        }
        """
    );

    var diagnostic = Assert.Single(result.Diagnostics, item => item.Id == "EXPOJSI006");
    Assert.Contains("Math", diagnostic.GetMessage());
    Assert.DoesNotContain("ModuleRegistry.DefineModule(context.Runtime, modules, \"Math\")", string.Join("\n", result.GeneratedSources.Select(source => source.Text)));
  }
}
