using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Expo.ModulesCore.Generator;

public sealed partial class ExpoModulesGenerator
{
  private static void EmitProvider(
      SourceProductionContext context,
      string assemblyName,
      IEnumerable<ExpoModuleModel> modules,
      IEnumerable<ExpoSharedObjectModel> sharedObjects)
  {
    var sharedObjectModels = sharedObjects.ToArray();
    foreach (var diagnostic in sharedObjectModels.SelectMany(sharedObject => sharedObject.Diagnostics.Values))
    {
      context.ReportDiagnostic(ToDiagnostic(diagnostic));
    }

    var moduleModels = modules.ToArray();
    var duplicateModuleNames = new HashSet<string>(
        moduleModels
            .GroupBy(module => module.ModuleName)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key),
        StringComparer.Ordinal
    );

    foreach (var diagnostic in moduleModels.SelectMany(module => module.Diagnostics.Values))
    {
      context.ReportDiagnostic(ToDiagnostic(diagnostic));
    }

    // The owning module's full JavaScript namespace is validated across the whole
    // compilation before any module is emitted.
    var ownershipDiagnostics = ValidateSharedObjectOwnership(
        moduleModels,
        sharedObjectModels,
        out var emittableClassesByModuleName);
    foreach (var diagnostic in ownershipDiagnostics)
    {
      context.ReportDiagnostic(ToDiagnostic(diagnostic));
    }

    foreach (var module in moduleModels)
    {
      EmitEventPartial(context, module);
    }
    foreach (var sharedObject in sharedObjectModels)
    {
      EmitSharedObjectEventPartial(context, sharedObject);
    }

    foreach (var group in moduleModels.GroupBy(module => module.ModuleName))
    {
      var duplicateModules = group.ToArray();
      if (duplicateModules.Length <= 1)
      {
        continue;
      }

      context.ReportDiagnostic(ToDiagnostic(new ExpoDiagnosticModel(
          ExpoModulesDiagnostics.DuplicateModuleName.Id,
          duplicateModules[1].Location,
          new EquatableArray<string>(new[] { group.Key })
      )));
    }

    moduleModels = moduleModels
        .Where(module =>
            module.ConstructorStrategy != ExpoModuleConstructorStrategy.Unsupported &&
            !duplicateModuleNames.Contains(module.ModuleName))
        .ToArray();

    var providerTypeName = $"ExpoModulesProvider_{SanitizeIdentifier(assemblyName)}";

    IReadOnlyList<ExpoSharedObjectModel> GetEmittableClasses(ExpoModuleModel module) =>
        emittableClassesByModuleName.TryGetValue(module.ModuleName, out var classes)
            ? classes
            : Array.Empty<ExpoSharedObjectModel>();
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated/>");
    builder.AppendLine("#nullable enable");
    builder.AppendLine("using Expo.ModulesCore;");
    builder.AppendLine("using Expo.ModulesCore.Codecs;");
    builder.AppendLine();
    builder.AppendLine("namespace Expo.ModulesCore.Generated;");
    builder.AppendLine();
    builder.AppendLine($"public static class {providerTypeName}");
    builder.AppendLine("{");
    var emittedRecordTypes = new HashSet<string>(StringComparer.Ordinal);
    foreach (var recordCodec in moduleModels
                 .SelectMany(module => module.RecordCodecs.Values)
                 .Concat(moduleModels.SelectMany(module =>
                     GetEmittableClasses(module).SelectMany(sharedObject => sharedObject.RecordCodecs.Values))))
    {
      if (emittedRecordTypes.Add(recordCodec.RecordTypeName))
      {
        EmitRecordCodec(builder, recordCodec);
      }
    }

    builder.AppendLine("  public static void Register(global::Expo.ModulesCore.DotnetRuntimeContext context)");
    builder.AppendLine("  {");
    builder.AppendLine("    global::System.ArgumentNullException.ThrowIfNull(context);");
    foreach (var module in moduleModels)
    {
      builder.AppendLine("    context.ModuleRegistry.RegisterLazyModule(");
      builder.AppendLine("        new global::Expo.ModulesCore.LazyModuleDefinition(");
      builder.AppendLine($"            \"{EscapeString(module.ModuleName)}\",");
      builder.AppendLine($"            static (context, modules) => {GetModuleRegistrationFunctionName(module)}(context, modules)");
      builder.AppendLine("        )");
      builder.AppendLine("    );");
    }
    builder.AppendLine("  }");
    builder.AppendLine();
    builder.AppendLine("  public static void Register(global::Expo.ModulesCore.DotnetRuntimeContext context, global::Expo.JSI.JavaScriptObject modules)");
    builder.AppendLine("  {");
    builder.AppendLine("    global::System.ArgumentNullException.ThrowIfNull(context);");
    builder.AppendLine("    global::System.ArgumentNullException.ThrowIfNull(modules);");
    foreach (var module in moduleModels)
    {
      builder.AppendLine($"    using var module_{SanitizeIdentifier(module.ModuleName)} = {GetModuleRegistrationFunctionName(module)}(context, modules);");
    }
    builder.AppendLine("  }");
    foreach (var module in moduleModels)
    {
      EmitModuleRegistrationFunction(builder, module, GetEmittableClasses(module));
    }
    foreach (var module in moduleModels)
    {
      EmitTypedEventProviderHelpers(builder, module);
    }
    foreach (var module in moduleModels)
    {
      foreach (var function in module.Functions.Values)
      {
        EmitHostFunction(builder, module, function);
      }
      foreach (var property in module.Properties.Values)
      {
        EmitPropertyGetter(builder, module, property);
        if (property.HasSetter)
        {
          EmitPropertySetter(builder, module, property);
        }
      }
      if (module.StartObservingHooks.Values.Count > 0)
      {
        EmitObservingHookFunction(builder, module, "startObserving", module.StartObservingHooks.Values);
      }
      if (module.StopObservingHooks.Values.Count > 0)
      {
        EmitObservingHookFunction(builder, module, "stopObserving", module.StopObservingHooks.Values);
      }
      foreach (var sharedObject in GetEmittableClasses(module))
      {
        EmitSharedObjectClassGlue(builder, module, sharedObject);
      }
    }
    builder.AppendLine("}");

    context.AddSource($"{providerTypeName}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
  }

  /// <summary>
  /// Names one emitted shared-object member host function: its generated method name, the
  /// diagnostic label used in argument-count errors, and the exact receiver type resolved through
  /// <c>SharedObjectCodec&lt;T&gt;</c> before authored code runs.
  /// </summary>
  private sealed record SharedObjectHostTarget(
      string HostFunctionName,
      string Label,
      string ReceiverTypeName);

  private static string GetSharedObjectIdentifier(
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject) =>
      $"{SanitizeIdentifier(module.ModuleName)}_{SanitizeIdentifier(sharedObject.JavaScriptClassName)}";

  private static string GetSharedObjectFactoryName(
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject) =>
      $"ConstructSharedObject_{GetSharedObjectIdentifier(module, sharedObject)}";

  private static string GetSharedObjectMemberInstallerName(
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject) =>
      $"InstallSharedObjectMembers_{GetSharedObjectIdentifier(module, sharedObject)}";

  private static string GetSharedObjectFunctionName(
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject,
      ExpoFunctionModel function) =>
      $"InvokeSharedObject_{GetSharedObjectIdentifier(module, sharedObject)}_{SanitizeIdentifier(function.JavaScriptName)}";

  private static string GetSharedObjectPropertyGetterName(
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject,
      ExpoPropertyModel property) =>
      $"GetSharedObjectProperty_{GetSharedObjectIdentifier(module, sharedObject)}_{SanitizeIdentifier(property.JavaScriptName)}";

  private static string GetSharedObjectPropertySetterName(
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject,
      ExpoPropertyModel property) =>
      $"SetSharedObjectProperty_{GetSharedObjectIdentifier(module, sharedObject)}_{SanitizeIdentifier(property.JavaScriptName)}";

  private static string GetSharedObjectEventInitializerName(
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject) =>
      $"InitializeSharedObjectEvents_{GetSharedObjectIdentifier(module, sharedObject)}";

  private static void EmitSharedObjectClassGlue(
      StringBuilder builder,
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject)
  {
    if (sharedObject.Constructor is not null)
    {
      EmitSharedObjectFactory(builder, module, sharedObject);
    }

    if (sharedObject.Events.Values.Any(@event => @event.IsDispatchable))
    {
      EmitSharedObjectEventProviderHelper(builder, module, sharedObject);
    }

    var hasMembers = sharedObject.Functions.Values.Count > 0 ||
        sharedObject.Properties.Values.Count > 0 ||
        sharedObject.Events.Values.Any(@event => @event.IsDispatchable);
    if (hasMembers)
    {
      EmitSharedObjectMemberInstaller(builder, module, sharedObject);
    }

    foreach (var function in sharedObject.Functions.Values)
    {
      EmitHostFunction(
          builder,
          module,
          function,
          new SharedObjectHostTarget(
              GetSharedObjectFunctionName(module, sharedObject, function),
              sharedObject.JavaScriptClassName,
              sharedObject.FullyQualifiedTypeName
          )
      );
    }
    foreach (var property in sharedObject.Properties.Values)
    {
      EmitPropertyGetter(
          builder,
          module,
          property,
          new SharedObjectHostTarget(
              GetSharedObjectPropertyGetterName(module, sharedObject, property),
              sharedObject.JavaScriptClassName,
              sharedObject.FullyQualifiedTypeName
          )
      );
      if (property.HasSetter)
      {
        EmitPropertySetter(
            builder,
            module,
            property,
            new SharedObjectHostTarget(
                GetSharedObjectPropertySetterName(module, sharedObject, property),
                sharedObject.JavaScriptClassName,
                sharedObject.FullyQualifiedTypeName
            )
        );
      }
    }
  }

  private static void EmitSharedObjectFactory(
      StringBuilder builder,
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject)
  {
    var constructor = sharedObject.Constructor!;
    var parameters = constructor.Parameters.Values;
    var requiredCount = parameters.Count(parameter => !parameter.HasDefaultValue);

    builder.AppendLine();
    builder.AppendLine($"  private static global::Expo.ModulesCore.SharedObject {GetSharedObjectFactoryName(module, sharedObject)}(");
    builder.AppendLine("      global::Expo.JSI.JavaScriptRuntime runtime,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptArrayRef arguments,");
    builder.AppendLine("      object context)");
    builder.AppendLine("  {");
    builder.AppendLine($"    GeneratedSharedObjectClass.RequireArgumentCount(\"{EscapeString(sharedObject.JavaScriptClassName)}\", arguments, {requiredCount}, {parameters.Count});");
    for (var index = 0; index < parameters.Count; index++)
    {
      var parameter = parameters[index];
      var decodeExpression = GetDecodeExpression(
          parameter.CodecExpression,
          index,
          "runtime",
          parameter.RequiresRuntimeContext
      );
      if (parameter.HasDefaultValue)
      {
        decodeExpression =
            $"arguments.Length <= {index} || arguments.GetValue({index}).Kind == global::Expo.JSI.JavaScriptValueKind.Undefined ? {parameter.DefaultValueExpression} : {decodeExpression}";
      }
      var declaration = parameter.OwnsDecodedValue ? "using var" : "var";
      builder.AppendLine($"    {declaration} {GetParameterLocalName(index)} = {decodeExpression};");
    }

    var argumentList = string.Join(
        ", ",
        parameters.Select((_, index) => GetParameterLocalName(index))
    );
    builder.AppendLine($"    return new {sharedObject.FullyQualifiedTypeName}({argumentList});");
    builder.AppendLine("  }");
  }

  private static void EmitSharedObjectEventProviderHelper(
      StringBuilder builder,
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject)
  {
    var events = sharedObject.Events.Values.Where(@event => @event.IsDispatchable).ToArray();
    builder.AppendLine();
    builder.AppendLine($"  private static void {GetSharedObjectEventInitializerName(module, sharedObject)}(");
    builder.AppendLine("      global::Expo.ModulesCore.DotnetRuntimeContext context,");
    builder.AppendLine($"      {sharedObject.FullyQualifiedTypeName} sharedObject)");
    builder.AppendLine("  {");
    builder.AppendLine("    sharedObject.__ExpoModulesCoreInitializeSharedObjectEvents(");
    builder.AppendLine("        context,");
    for (var index = 0; index < events.Length; index++)
    {
      var @event = events[index];
      var valueParameter = GetEventValueParameterName(@event);
      var expression = @event.PayloadKind switch
      {
        ExpoEventPayloadKind.None =>
            $"() => global::Expo.ModulesCore.GeneratedSharedObjectEvents.EmitAsync(context, sharedObject, \"{EscapeString(@event.JavaScriptName)}\")",
        ExpoEventPayloadKind.Codec =>
            $"{valueParameter} => global::Expo.ModulesCore.GeneratedSharedObjectEvents.EmitAsync<{@event.CodecExpression}, {@event.PayloadTypeName}>(context, sharedObject, \"{EscapeString(@event.JavaScriptName)}\", {valueParameter})",
        ExpoEventPayloadKind.JavaScriptValue or ExpoEventPayloadKind.ArrayBuffer =>
            $"{valueParameter} => global::Expo.ModulesCore.GeneratedSharedObjectEvents.EmitAsync(context, sharedObject, \"{EscapeString(@event.JavaScriptName)}\", {valueParameter})",
        _ => throw new InvalidOperationException($"Unknown event payload kind: {@event.PayloadKind}"),
      };
      builder.AppendLine($"        {expression}{(index == events.Length - 1 ? ");" : ",")}");
    }
    builder.AppendLine("  }");
  }

  private static void EmitSharedObjectMemberInstaller(
      StringBuilder builder,
      ExpoModuleModel module,
      ExpoSharedObjectModel sharedObject)
  {
    builder.AppendLine();
    builder.AppendLine($"  private static void {GetSharedObjectMemberInstallerName(module, sharedObject)}(");
    builder.AppendLine("      global::Expo.ModulesCore.DotnetRuntimeContext context,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptObject prototype)");
    builder.AppendLine("  {");
    foreach (var function in sharedObject.Functions.Values)
    {
      builder.AppendLine(function.IsAsync
          ? "    GeneratedFunction.DefineAsync("
          : "    GeneratedFunction.DefineSync(");
      builder.AppendLine("        context,");
      builder.AppendLine("        prototype,");
      builder.AppendLine($"        \"{EscapeString(function.JavaScriptName)}\",");
      builder.AppendLine($"        {GetRequiredParameterCount(function)},");
      builder.AppendLine($"        {GetSharedObjectFunctionName(module, sharedObject, function)},");
      builder.AppendLine($"        typeof({sharedObject.FullyQualifiedTypeName})");
      builder.AppendLine("    );");
    }
    foreach (var property in sharedObject.Properties.Values)
    {
      builder.AppendLine("    GeneratedProperty.Define(");
      builder.AppendLine("        context,");
      builder.AppendLine("        prototype,");
      builder.AppendLine($"        \"{EscapeString(property.JavaScriptName)}\",");
      builder.AppendLine($"        {GetSharedObjectPropertyGetterName(module, sharedObject, property)},");
      builder.AppendLine(property.HasSetter
          ? $"        {GetSharedObjectPropertySetterName(module, sharedObject, property)},"
          : "        null,");
      builder.AppendLine($"        typeof({sharedObject.FullyQualifiedTypeName})");
      builder.AppendLine("    );");
    }
    builder.AppendLine("  }");
  }

  private static void EmitModuleRegistrationFunction(
      StringBuilder builder,
      ExpoModuleModel module,
      IReadOnlyList<ExpoSharedObjectModel> ownedClasses)
  {
    var moduleVariable = $"module_{SanitizeIdentifier(module.ModuleName)}";
    var moduleInstanceVariable = $"instance_{SanitizeIdentifier(module.ModuleName)}";
    var hasEvents = module.EventNames.Values.Count > 0;
    var typedEvents = module.Events.Values.Where(@event => @event.IsDispatchable).ToArray();
    var factoryExpression = typedEvents.Length > 0
        ? $"() => {GetEventFactoryName(module)}(context)"
        : module.ConstructorStrategy == ExpoModuleConstructorStrategy.RuntimeContext
        ? $"() => new {module.FullyQualifiedTypeName}(context)"
        : $"static () => new {module.FullyQualifiedTypeName}()";
    var onCreateExpression = GetLifecycleHookExpression(module.OnCreateHook);
    var onDestroyExpression = GetLifecycleHookExpression(module.OnDestroyHook);

    builder.AppendLine();
    builder.AppendLine($"  private static global::Expo.JSI.JavaScriptObject {GetModuleRegistrationFunctionName(module)}(");
    builder.AppendLine("      global::Expo.ModulesCore.DotnetRuntimeContext context,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptObject modules)");
    builder.AppendLine("  {");
    builder.AppendLine(hasEvents
        ? $"    var {moduleVariable} = context.ModuleRegistry.DefineNativeModule(modules, \"{EscapeString(module.ModuleName)}\");"
        : $"    var {moduleVariable} = context.ModuleRegistry.DefineModule(modules, \"{EscapeString(module.ModuleName)}\");");
    builder.AppendLine("    try");
    builder.AppendLine("    {");
    builder.AppendLine(module.OnCreateHook is null && module.OnDestroyHook is null
        ? $"      var {moduleInstanceVariable} = context.ModuleRegistry.GetOrCreateModule(\"{EscapeString(module.ModuleName)}\", {factoryExpression});"
        : $"      var {moduleInstanceVariable} = context.ModuleRegistry.GetOrCreateModule(\"{EscapeString(module.ModuleName)}\", {factoryExpression}, {onCreateExpression}, {onDestroyExpression});");
    if (typedEvents.Length > 0)
    {
      builder.AppendLine($"      {GetEventInitializerName(module)}(context, {moduleInstanceVariable});");
    }
    if (hasEvents)
    {
      builder.AppendLine(
          $"      context.Events.Attach({moduleInstanceVariable}, {moduleVariable}, \"{EscapeString(module.ModuleName)}\", new[] {{ {string.Join(", ", module.EventNames.Values.Select(name => $"\"{EscapeString(name)}\""))} }});"
      );
    }
    if (module.StartObservingHooks.Values.Count > 0)
    {
      EmitObservingHookRegistration(builder, module, moduleVariable, moduleInstanceVariable, "startObserving", "      ");
    }
    if (module.StopObservingHooks.Values.Count > 0)
    {
      EmitObservingHookRegistration(builder, module, moduleVariable, moduleInstanceVariable, "stopObserving", "      ");
    }
    foreach (var function in module.Functions.Values)
    {
      builder.AppendLine(function.IsAsync
          ? "      GeneratedFunction.DefineAsync("
          : "      GeneratedFunction.DefineSync(");
      builder.AppendLine("          context,");
      builder.AppendLine($"          {moduleVariable},");
      builder.AppendLine($"          \"{EscapeString(function.JavaScriptName)}\",");
      builder.AppendLine($"          {GetRequiredParameterCount(function)},");
      builder.AppendLine($"          {GetHostFunctionName(module, function)},");
      builder.AppendLine($"          {moduleInstanceVariable}");
      builder.AppendLine("      );");
    }
    foreach (var property in module.Properties.Values)
    {
      builder.AppendLine("      GeneratedProperty.Define(");
      builder.AppendLine("          context,");
      builder.AppendLine($"          {moduleVariable},");
      builder.AppendLine($"          \"{EscapeString(property.JavaScriptName)}\",");
      builder.AppendLine($"          {GetPropertyGetterFunctionName(module, property)},");
      builder.AppendLine(property.HasSetter
          ? $"          {GetPropertySetterFunctionName(module, property)},"
          : "          null,");
      builder.AppendLine($"          {moduleInstanceVariable}");
      builder.AppendLine("      );");
    }
    foreach (var sharedObject in ownedClasses)
    {
      var sharedEvents = sharedObject.Events.Values.Where(@event => @event.IsDispatchable).ToArray();
      var hasMembers = sharedObject.Functions.Values.Count > 0 ||
          sharedObject.Properties.Values.Count > 0;
      builder.AppendLine("      GeneratedSharedObjectClass.Install(");
      builder.AppendLine("          context,");
      builder.AppendLine($"          {moduleVariable},");
      builder.AppendLine($"          typeof({sharedObject.FullyQualifiedTypeName}),");
      builder.AppendLine($"          \"{EscapeString(sharedObject.JavaScriptClassName)}\",");
      builder.AppendLine($"          {(sharedObject.Constructor?.Parameters.Values.Count ?? 0)},");
      builder.AppendLine(sharedObject.Constructor is null
          ? "          null,"
          : $"          {GetSharedObjectFactoryName(module, sharedObject)},");
      builder.AppendLine(hasMembers
          ? $"          {GetSharedObjectMemberInstallerName(module, sharedObject)},"
          : "          null,");
      builder.AppendLine(sharedEvents.Length > 0
          ? $"          new[] {{ {string.Join(", ", sharedEvents.Select(@event => $"\"{EscapeString(@event.JavaScriptName)}\""))} }},"
          : "          null,");
      builder.AppendLine(sharedEvents.Length > 0
          ? $"          static (context, sharedObject) => {GetSharedObjectEventInitializerName(module, sharedObject)}(context, ({sharedObject.FullyQualifiedTypeName})sharedObject)"
          : "          null");
      builder.AppendLine("      );");
    }
    builder.AppendLine($"      return {moduleVariable};");
    builder.AppendLine("    }");
    builder.AppendLine("    catch");
    builder.AppendLine("    {");
    builder.AppendLine($"      {moduleVariable}.Dispose();");
    builder.AppendLine("      throw;");
    builder.AppendLine("    }");
    builder.AppendLine("  }");
  }

  private static void EmitEventPartial(SourceProductionContext context, ExpoModuleModel module)
  {
    var events = module.Events.Values.Where(@event => @event.IsShapeValid).ToArray();
    if (events.Length == 0)
    {
      return;
    }

    var dispatchableEvents = events.Where(@event => @event.IsDispatchable).ToArray();
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated/>");
    builder.AppendLine("#nullable enable");
    if (module.Namespace.Length > 0)
    {
      builder.AppendLine($"namespace {module.Namespace};");
      builder.AppendLine();
    }
    builder.AppendLine($"{module.Accessibility} partial class {EscapeIdentifier(module.SimpleTypeName)}");
    builder.AppendLine("{");
    if (dispatchableEvents.Length > 0)
    {
      builder.AppendLine("  private readonly object __expoEventInitializationGate = new();");
      builder.AppendLine("  private global::Expo.ModulesCore.DotnetRuntimeContext? __expoEventContext;");
    }
    foreach (var @event in dispatchableEvents)
    {
      builder.AppendLine($"  private {(@event.IsStatic ? "static " : string.Empty)}{@event.DelegateTypeName}? {GetEventBackingFieldName(@event)};");
    }
    foreach (var @event in events)
    {
      builder.AppendLine();
      builder.AppendLine($"  {@event.DeclarationModifiers} {@event.DelegateTypeName} {EscapeIdentifier(@event.PropertyName)}");
      builder.AppendLine("  {");
      if (@event.GetterAccessor.Length > 0)
      {
        var getterExpression = @event.IsDispatchable
            ? $"{GetEventBackingFieldName(@event)} ?? throw new global::System.InvalidOperationException(\"Event member '{module.SimpleTypeName}.{@event.PropertyName}' is unavailable before module registration.\")"
            : $"throw new global::System.InvalidOperationException(\"Event member '{module.SimpleTypeName}.{@event.PropertyName}' cannot be used because its declaration is invalid.\")";
        builder.AppendLine($"    {@event.GetterAccessor} => {getterExpression};");
      }
      if (@event.SetterAccessor.Length > 0)
      {
        builder.AppendLine($"    {@event.SetterAccessor} => throw new global::System.InvalidOperationException(\"Event member '{module.SimpleTypeName}.{@event.PropertyName}' cannot be assigned.\");");
      }
      builder.AppendLine("  }");
    }
    if (dispatchableEvents.Length > 0)
    {
      builder.AppendLine();
      builder.AppendLine("  internal void __ExpoModulesCoreInitializeEvents(");
      builder.AppendLine("      global::Expo.ModulesCore.DotnetRuntimeContext context,");
      for (var index = 0; index < dispatchableEvents.Length; index++)
      {
        var @event = dispatchableEvents[index];
        builder.AppendLine($"      {@event.DelegateTypeName} {GetEventParameterName(@event)}{(index == dispatchableEvents.Length - 1 ? ")" : ",")}");
      }
      builder.AppendLine("  {");
      builder.AppendLine("    lock (__expoEventInitializationGate)");
      builder.AppendLine("    {");
      builder.AppendLine("      if (__expoEventContext is not null)");
      builder.AppendLine("      {");
      builder.AppendLine("        if (!global::System.Object.ReferenceEquals(__expoEventContext, context))");
      builder.AppendLine("          throw new global::System.InvalidOperationException(\"Module event members cannot be rebound to a different runtime context.\");");
      builder.AppendLine("        return;");
      builder.AppendLine("      }");
      foreach (var @event in dispatchableEvents)
      {
        builder.AppendLine($"      {GetEventBackingFieldName(@event)} = {GetEventParameterName(@event)} ?? throw new global::System.ArgumentNullException(nameof({GetEventParameterName(@event)}));");
      }
      builder.AppendLine("      __expoEventContext = context ?? throw new global::System.ArgumentNullException(nameof(context));");
      builder.AppendLine("    }");
      builder.AppendLine("  }");
    }
    builder.AppendLine("}");
    context.AddSource(GetEventHintName(module), SourceText.From(builder.ToString(), Encoding.UTF8));
  }

  private static void EmitTypedEventProviderHelpers(StringBuilder builder, ExpoModuleModel module)
  {
    var events = module.Events.Values.Where(@event => @event.IsDispatchable).ToArray();
    if (events.Length == 0)
    {
      return;
    }
    builder.AppendLine();
    builder.AppendLine($"  private static {module.FullyQualifiedTypeName} {GetEventFactoryName(module)}(global::Expo.ModulesCore.DotnetRuntimeContext context)");
    builder.AppendLine("  {");
    var creation = module.ConstructorStrategy == ExpoModuleConstructorStrategy.RuntimeContext
        ? $"new {module.FullyQualifiedTypeName}(context)"
        : $"new {module.FullyQualifiedTypeName}()";
    builder.AppendLine($"    var module = {creation};");
    builder.AppendLine($"    {GetEventInitializerName(module)}(context, module);");
    builder.AppendLine("    return module;");
    builder.AppendLine("  }");
    builder.AppendLine();
    builder.AppendLine($"  private static void {GetEventInitializerName(module)}(");
    builder.AppendLine("      global::Expo.ModulesCore.DotnetRuntimeContext context,");
    builder.AppendLine($"      {module.FullyQualifiedTypeName} module)");
    builder.AppendLine("  {");
    builder.AppendLine("    var emitter = context.Events;");
    builder.AppendLine("    module.__ExpoModulesCoreInitializeEvents(");
    builder.AppendLine("        context,");
    for (var index = 0; index < events.Length; index++)
    {
      var @event = events[index];
      builder.AppendLine($"        {GetEventDelegateExpression(@event)}{(index == events.Length - 1 ? ");" : ",")}");
    }
    builder.AppendLine("  }");
  }

  private static void EmitSharedObjectEventPartial(
      SourceProductionContext context,
      ExpoSharedObjectModel sharedObject)
  {
    var events = sharedObject.Events.Values.Where(@event => @event.IsShapeValid).ToArray();
    if (events.Length == 0)
    {
      return;
    }

    var dispatchableEvents = events.Where(@event => @event.IsDispatchable).ToArray();
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated/>");
    builder.AppendLine("#nullable enable");
    if (sharedObject.Namespace.Length > 0)
    {
      builder.AppendLine($"namespace {sharedObject.Namespace};");
      builder.AppendLine();
    }
    builder.AppendLine($"{sharedObject.Accessibility} partial {sharedObject.DeclarationKind} {EscapeIdentifier(sharedObject.SimpleTypeName)}");
    builder.AppendLine("{");
    if (dispatchableEvents.Length > 0)
    {
      builder.AppendLine("  private readonly object __expoSharedObjectEventInitializationGate = new();");
      builder.AppendLine("  private global::Expo.ModulesCore.DotnetRuntimeContext? __expoSharedObjectEventContext;");
    }
    foreach (var @event in dispatchableEvents)
    {
      builder.AppendLine($"  private {@event.DelegateTypeName}? __expoSharedObjectEvent_{SanitizeIdentifier(@event.PropertyName)};");
    }
    foreach (var @event in events)
    {
      builder.AppendLine();
      builder.AppendLine($"  {@event.DeclarationModifiers} {@event.DelegateTypeName} {EscapeIdentifier(@event.PropertyName)}");
      builder.AppendLine("  {");
      if (@event.GetterAccessor.Length > 0)
      {
        var expression = @event.IsDispatchable
            ? $"__expoSharedObjectEvent_{SanitizeIdentifier(@event.PropertyName)} ?? throw new global::System.InvalidOperationException(\"Event member '{sharedObject.SimpleTypeName}.{@event.PropertyName}' is unavailable before shared-object pairing.\")"
            : $"throw new global::System.InvalidOperationException(\"Event member '{sharedObject.SimpleTypeName}.{@event.PropertyName}' cannot be used because its declaration is invalid.\")";
        builder.AppendLine($"    {@event.GetterAccessor} => {expression};");
      }
      if (@event.SetterAccessor.Length > 0)
      {
        builder.AppendLine($"    {@event.SetterAccessor} => throw new global::System.InvalidOperationException(\"Event member '{sharedObject.SimpleTypeName}.{@event.PropertyName}' cannot be assigned.\");");
      }
      builder.AppendLine("  }");
    }
    if (dispatchableEvents.Length > 0)
    {
      builder.AppendLine();
      builder.AppendLine("  internal void __ExpoModulesCoreInitializeSharedObjectEvents(");
      builder.AppendLine("      global::Expo.ModulesCore.DotnetRuntimeContext context,");
      for (var index = 0; index < dispatchableEvents.Length; index++)
      {
        var @event = dispatchableEvents[index];
        builder.AppendLine($"      {@event.DelegateTypeName} {GetEventParameterName(@event)}{(index == dispatchableEvents.Length - 1 ? ")" : ",")}");
      }
      builder.AppendLine("  {");
      builder.AppendLine("    lock (__expoSharedObjectEventInitializationGate)");
      builder.AppendLine("    {");
      builder.AppendLine("      if (__expoSharedObjectEventContext is not null)");
      builder.AppendLine("      {");
      builder.AppendLine("        if (!global::System.Object.ReferenceEquals(__expoSharedObjectEventContext, context))");
      builder.AppendLine("          throw new global::System.InvalidOperationException(\"Shared-object event members cannot be rebound to a different runtime context.\");");
      builder.AppendLine("        return;");
      builder.AppendLine("      }");
      foreach (var @event in dispatchableEvents)
      {
        builder.AppendLine($"      __expoSharedObjectEvent_{SanitizeIdentifier(@event.PropertyName)} = {GetEventParameterName(@event)} ?? throw new global::System.ArgumentNullException(nameof({GetEventParameterName(@event)}));");
      }
      builder.AppendLine("      __expoSharedObjectEventContext = context ?? throw new global::System.ArgumentNullException(nameof(context));");
      builder.AppendLine("    }");
      builder.AppendLine("  }");
    }
    builder.AppendLine("}");
    context.AddSource(
        $"{SanitizeIdentifier(sharedObject.FullyQualifiedTypeName)}_{GetStableHash(sharedObject.FullyQualifiedTypeName):X8}.SharedObjectEvents.g.cs",
        SourceText.From(builder.ToString(), Encoding.UTF8)
    );
  }

  private static string GetEventDelegateExpression(ExpoEventModel @event) => @event.PayloadKind switch
  {
    ExpoEventPayloadKind.None => $"() => emitter.EmitAsync(module, \"{EscapeString(@event.JavaScriptName)}\")",
    ExpoEventPayloadKind.Codec => $"{GetEventValueParameterName(@event)} => emitter.EmitAsync<{@event.CodecExpression}, {@event.PayloadTypeName}>(module, \"{EscapeString(@event.JavaScriptName)}\", {GetEventValueParameterName(@event)})",
    ExpoEventPayloadKind.JavaScriptValue or ExpoEventPayloadKind.ArrayBuffer =>
        $"{GetEventValueParameterName(@event)} => emitter.EmitAsync(module, \"{EscapeString(@event.JavaScriptName)}\", {GetEventValueParameterName(@event)})",
    _ => throw new InvalidOperationException($"Unknown event payload kind: {@event.PayloadKind}"),
  };

  private static string GetEventFactoryName(ExpoModuleModel module) =>
      $"Create{SanitizeIdentifier(module.ModuleName)}";

  private static string GetEventInitializerName(ExpoModuleModel module) =>
      $"Initialize{SanitizeIdentifier(module.ModuleName)}Events";

  private static string GetEventBackingFieldName(ExpoEventModel @event) =>
      $"__expoEvent_{SanitizeIdentifier(@event.PropertyName)}";

  private static string GetEventParameterName(ExpoEventModel @event) =>
      $"on{SanitizeIdentifier(@event.PropertyName)}";

  private static string GetEventValueParameterName(ExpoEventModel @event) =>
      $"{LowerCamel(SanitizeIdentifier(@event.PropertyName))}Value";

  private static string GetEventHintName(ExpoModuleModel module) =>
      $"{SanitizeIdentifier(module.FullyQualifiedTypeName)}_{GetStableHash(module.FullyQualifiedTypeName):X8}.Events.g.cs";

  private static uint GetStableHash(string value)
  {
    const uint offsetBasis = 2166136261;
    const uint prime = 16777619;
    var hash = offsetBasis;
    foreach (var character in value)
    {
      hash = (hash ^ character) * prime;
    }
    return hash;
  }

  private static Diagnostic ToDiagnostic(ExpoDiagnosticModel model)
  {
    var descriptor = model.DescriptorId switch
    {
      "EXPOJSI001" => ExpoModulesDiagnostics.UnsupportedParameterType,
      "EXPOJSI002" => ExpoModulesDiagnostics.UnsupportedReturnType,
      "EXPOJSI003" => ExpoModulesDiagnostics.UnsupportedModuleConstructor,
      "EXPOJSI004" => ExpoModulesDiagnostics.UnsupportedJSMethodShape,
      "EXPOJSI005" => ExpoModulesDiagnostics.DuplicateJavaScriptFunctionName,
      "EXPOJSI006" => ExpoModulesDiagnostics.DuplicateModuleName,
      "EXPOJSI007" => ExpoModulesDiagnostics.UnsupportedRecordField,
      "EXPOJSI008" => ExpoModulesDiagnostics.UnsupportedCallbackCodec,
      "EXPOJSI009" => ExpoModulesDiagnostics.InvalidEventName,
      "EXPOJSI010" => ExpoModulesDiagnostics.InvalidObservingHook,
      "EXPOJSI011" => ExpoModulesDiagnostics.InvalidLifecycleHook,
      "EXPOJSI012" => ExpoModulesDiagnostics.AsyncSpanParameter,
      "EXPOJSI013" => ExpoModulesDiagnostics.MultipleSpanParameters,
      "EXPOJSI014" => ExpoModulesDiagnostics.UnsupportedJSPropertyShape,
      "EXPOJSI015" => ExpoModulesDiagnostics.UnsupportedJSPropertyType,
      "EXPOJSI016" => ExpoModulesDiagnostics.DuplicateJavaScriptMemberName,
      "EXPOJSI017" => ExpoModulesDiagnostics.ReservedObservingPropertyName,
      "EXPOJSI018" => ExpoModulesDiagnostics.UnsupportedEventProperty,
      "EXPOJSI019" => ExpoModulesDiagnostics.UnsupportedEventPayload,
      "EXPOJSI020" => ExpoModulesDiagnostics.DuplicateEventName,
      "EXPOJSI021" => ExpoModulesDiagnostics.InvalidSharedObjectDeclaration,
      "EXPOJSI022" => ExpoModulesDiagnostics.InvalidSharedObjectConstructor,
      "EXPOJSI023" => ExpoModulesDiagnostics.UnsupportedSharedObjectUsage,
      "EXPOJSI024" => ExpoModulesDiagnostics.InvalidSharedObjectOwnership,
      "EXPOJSI025" => ExpoModulesDiagnostics.InvalidSharedObjectMemberName,
      "EXPOJSI026" => ExpoModulesDiagnostics.UnsupportedSharedObjectEventProperty,
      "EXPOJSI027" => ExpoModulesDiagnostics.UnsupportedSharedObjectEventPayload,
      "EXPOJSI028" => ExpoModulesDiagnostics.DuplicateSharedObjectEventName,
      _ => throw new InvalidOperationException($"Unknown diagnostic descriptor: {model.DescriptorId}"),
    };
    return Diagnostic.Create(descriptor, model.Location, model.Arguments.Values.Cast<object>().ToArray());
  }

  private static string GetLifecycleHookExpression(ExpoLifecycleHookModel? hook) =>
      hook is null ? "null" : $"static module => module.{hook.MethodName}()";

  private static void EmitObservingHookRegistration(
      StringBuilder builder,
      ExpoModuleModel module,
      string moduleVariable,
      string moduleInstanceVariable,
      string javaScriptName,
      string indent = "    ")
  {
    builder.AppendLine($"{indent}GeneratedFunction.DefineSync(");
    builder.AppendLine($"{indent}    context,");
    builder.AppendLine($"{indent}    {moduleVariable},");
    builder.AppendLine($"{indent}    \"{javaScriptName}\",");
    builder.AppendLine($"{indent}    1,");
    builder.AppendLine($"{indent}    {GetObservingHookFunctionName(module, javaScriptName)},");
    builder.AppendLine($"{indent}    {moduleInstanceVariable}");
    builder.AppendLine($"{indent});");
  }

  private static void EmitHostFunction(
      StringBuilder builder,
      ExpoModuleModel module,
      ExpoFunctionModel function,
      SharedObjectHostTarget? shared = null)
  {
    if (!function.IsAsync && function.Parameters.Values.Any(parameter =>
            parameter.PassingKind != ExpoParameterPassingKind.Codec))
    {
      EmitSpanHostFunction(builder, module, function, shared);
      return;
    }

    var hostFunctionName = shared?.HostFunctionName ?? GetHostFunctionName(module, function);
    var label = shared?.Label ?? module.ModuleName;

    builder.AppendLine();
    builder.AppendLine($"  private static global::Expo.JSI.JavaScriptValue {hostFunctionName}(");
    var runtimeParameterName = function.IsAsync ? "jsRuntime" : "runtime";
    // The shared receiver resolves through the codec (registry NativeState identity) before any
    // authored code runs; the local keeps the `module` name so the shared body emission below
    // stays identical for module-level and prototype-level members.
    var targetDeclaration = shared is null
        ? $"var module = ({module.FullyQualifiedTypeName})context;"
        : $"var module = SharedObjectCodec<{shared.ReceiverTypeName}>.Decode(thisValue, {runtimeParameterName}, GeneratedFunction.CurrentRuntimeContext);";
    builder.AppendLine($"      global::Expo.JSI.JavaScriptRuntime {runtimeParameterName},");
    builder.AppendLine("      global::Expo.JSI.JavaScriptValueRef thisValue,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptArguments arguments,");
    builder.AppendLine("      object context)");
    builder.AppendLine("  {");
    if (function.IsAsync)
    {
      for (var index = 0; index < function.Parameters.Values.Count; index++)
      {
        if (function.Parameters.Values[index].OwnsDecodedValue)
        {
          builder.AppendLine($"    {function.Parameters.Values[index].TypeName}? {GetParameterLocalName(index)} = null;");
        }
      }
    }

    if (function.IsAsync)
    {
      builder.AppendLine("    try");
      builder.AppendLine("    {");
      builder.AppendLine($"      GeneratedFunction.RequireArgumentCount(\"{EscapeString(label)}.{EscapeString(function.JavaScriptName)}\", arguments, {GetRequiredParameterCount(function)}, {function.Parameters.Values.Count});");
      builder.AppendLine($"      {targetDeclaration}");
      if (function.AsyncResultRequiresRuntimeContext)
      {
        // Capture the exact runtime context while the host-function frame is active; Promise
        // settlement runs after the frame exits and must never read the thread-static accessor.
        builder.AppendLine("      var __expoRuntimeContext = GeneratedFunction.CurrentRuntimeContext;");
      }
    }
    else
    {
      builder.AppendLine($"    GeneratedFunction.RequireArgumentCount(\"{EscapeString(label)}.{EscapeString(function.JavaScriptName)}\", arguments, {GetRequiredParameterCount(function)}, {function.Parameters.Values.Count});");
      builder.AppendLine();
      builder.AppendLine($"    {targetDeclaration}");
    }

    for (var index = 0; index < function.Parameters.Values.Count; index++)
    {
      var parameter = function.Parameters.Values[index];
      var parameterLocalName = GetParameterLocalName(index);
      if (function.IsAsync && parameter.OwnsDecodedValue)
      {
        builder.AppendLine($"      {parameterLocalName} = {GetParameterExpression(parameter, index, runtimeParameterName)};");
      }
      else
      {
        var declaration = parameter.OwnsDecodedValue ? "using var" : "var";
        builder.AppendLine(function.IsAsync
            ? $"      {declaration} {parameterLocalName} = {GetParameterExpression(parameter, index, runtimeParameterName)};"
            : $"    {declaration} {parameterLocalName} = {GetParameterExpression(parameter, index, runtimeParameterName)};");
      }
    }

    var argumentList = string.Join(
        ", ",
        function.Parameters.Values.Select((parameter, index) =>
            function.IsAsync && parameter.OwnsDecodedValue
                ? $"{GetParameterLocalName(index)}!"
                : GetParameterLocalName(index))
    );
    var disposeAsyncDecodedValues = function.Parameters.Values.Any(parameter => parameter.OwnsDecodedValue);
    if (function.IsAsync)
    {
      builder.AppendLine($"      var __expoTask = module.{function.MethodName}({argumentList});");
      builder.AppendLine($"      using var __expoPromiseValue = {runtimeParameterName}.CreatePromise(");
      builder.AppendLine("          async _ =>");
      builder.AppendLine("          {");
      if (disposeAsyncDecodedValues)
      {
        builder.AppendLine("            try");
        builder.AppendLine("            {");
      }

      var asyncIndent = disposeAsyncDecodedValues ? "              " : "            ";
      if (function.AsyncReturnsVoid)
      {
        builder.AppendLine($"{asyncIndent}await __expoTask.ConfigureAwait(false);");
        builder.AppendLine($"{asyncIndent}return global::Expo.JSI.JavaScriptPromiseResult.Resolve(static runtime => runtime.CreateUndefined());");
      }
      else if (function.AsyncResultCodecExpression == "JavaScriptValueCodec")
      {
        builder.AppendLine($"{asyncIndent}var __expoResult = await __expoTask.ConfigureAwait(false);");
        builder.AppendLine($"{asyncIndent}return global::Expo.JSI.JavaScriptPromiseResult.ResolveOwned(");
        builder.AppendLine($"{asyncIndent}    __expoResult,");
        builder.AppendLine($"{asyncIndent}    static (_, value) => value,");
        builder.AppendLine($"{asyncIndent}    static value => value.Dispose()");
        builder.AppendLine($"{asyncIndent});");
      }
      else if (function.AsyncResultCodecExpression == "ArrayBufferCodec")
      {
        builder.AppendLine($"{asyncIndent}var __expoResult = await __expoTask.ConfigureAwait(false);");
        builder.AppendLine($"{asyncIndent}return global::Expo.JSI.JavaScriptPromiseResult.ResolveOwned(");
        builder.AppendLine($"{asyncIndent}    __expoResult,");
        builder.AppendLine($"{asyncIndent}    static (runtime, value) =>");
        builder.AppendLine($"{asyncIndent}    {{");
        builder.AppendLine($"{asyncIndent}      try {{ return ArrayBufferCodec.Encode(value, runtime); }}");
        builder.AppendLine($"{asyncIndent}      finally {{ value.Dispose(); }}");
        builder.AppendLine($"{asyncIndent}    }},");
        builder.AppendLine($"{asyncIndent}    static value => value.Dispose()");
        builder.AppendLine($"{asyncIndent});");
      }
      else
      {
        var asyncEncodeContextArgument = function.AsyncResultRequiresRuntimeContext
            ? ", __expoRuntimeContext"
            : string.Empty;
        builder.AppendLine($"{asyncIndent}var __expoResult = await __expoTask.ConfigureAwait(false);");
        builder.AppendLine($"{asyncIndent}return global::Expo.JSI.JavaScriptPromiseResult.Resolve(runtime => {function.AsyncResultCodecExpression}.Encode(__expoResult, runtime{asyncEncodeContextArgument}));");
      }

      if (disposeAsyncDecodedValues)
      {
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");
        EmitDisposeDecodedValues(builder, function, "              ");
        builder.AppendLine("            }");
      }
      builder.AppendLine("          }");
      builder.AppendLine("      );");
      builder.AppendLine("      return __expoPromiseValue.AsValue();");
      builder.AppendLine("    }");
      builder.AppendLine("    catch (global::System.Exception exception)");
      builder.AppendLine("    {");
      if (disposeAsyncDecodedValues)
      {
        EmitDisposeDecodedValues(builder, function, "      ");
      }
      builder.AppendLine($"      return GeneratedFunction.CreateRejectedPromise({runtimeParameterName}, exception);");
      builder.AppendLine("    }");
    }
    else if (function.ReturnsVoid)
    {
      builder.AppendLine($"    module.{function.MethodName}({argumentList});");
      builder.AppendLine("    return runtime.CreateUndefined();");
    }
    else
    {
      if (function.ReturnPassingKind != ExpoReturnPassingKind.Codec)
      {
        builder.AppendLine($"    return ArrayBufferCodec.EncodeCopy(module.{function.MethodName}({argumentList}), runtime);");
      }
      else if (function.ReturnCodecExpression == "ArrayBufferCodec")
      {
        builder.AppendLine($"    using var __expoResult = module.{function.MethodName}({argumentList});");
        builder.AppendLine("    return ArrayBufferCodec.Encode(__expoResult, runtime);");
      }
      else if (function.ReturnCodecExpression == "JavaScriptValueCodec")
      {
        builder.AppendLine($"    return JavaScriptValueCodec.Encode(module.{function.MethodName}({argumentList}), runtime);");
      }
      else
      {
        var returnEncodeContextArgument = function.ReturnRequiresRuntimeContext
            ? ", GeneratedFunction.CurrentRuntimeContext"
            : string.Empty;
        builder.AppendLine($"    return {function.ReturnCodecExpression}.Encode(module.{function.MethodName}({argumentList}), runtime{returnEncodeContextArgument});");
      }
    }
    builder.AppendLine("  }");
  }

  private static void EmitPropertyGetter(
      StringBuilder builder,
      ExpoModuleModel module,
      ExpoPropertyModel property,
      SharedObjectHostTarget? shared = null)
  {
    var getterName = shared?.HostFunctionName ?? GetPropertyGetterFunctionName(module, property);
    var label = shared?.Label ?? module.ModuleName;
    var targetDeclaration = shared is null
        ? $"var module = ({module.FullyQualifiedTypeName})context;"
        : $"var module = SharedObjectCodec<{shared.ReceiverTypeName}>.Decode(thisValue, runtime, GeneratedFunction.CurrentRuntimeContext);";
    var encodeContextArgument = property.RequiresRuntimeContext
        ? ", GeneratedFunction.CurrentRuntimeContext"
        : string.Empty;

    builder.AppendLine();
    builder.AppendLine($"  private static global::Expo.JSI.JavaScriptValue {getterName}(");
    builder.AppendLine("      global::Expo.JSI.JavaScriptRuntime runtime,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptValueRef thisValue,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptArguments arguments,");
    builder.AppendLine("      object context)");
    builder.AppendLine("  {");
    builder.AppendLine($"    GeneratedFunction.RequireArgumentCount(\"{EscapeString(label)}.{EscapeString(property.JavaScriptName)}\", arguments, 0);");
    builder.AppendLine($"    {targetDeclaration}");
    if (property.CodecExpression == "ArrayBufferCodec")
    {
      builder.AppendLine($"    using var __expoResult = module.{property.PropertyName};");
      builder.AppendLine("    return ArrayBufferCodec.Encode(__expoResult, runtime);");
    }
    else if (property.CodecExpression == "JavaScriptValueCodec")
    {
      builder.AppendLine($"    return JavaScriptValueCodec.Encode(module.{property.PropertyName}, runtime);");
    }
    else
    {
      builder.AppendLine($"    return {property.CodecExpression}.Encode(module.{property.PropertyName}, runtime{encodeContextArgument});");
    }
    builder.AppendLine("  }");
  }

  private static void EmitPropertySetter(
      StringBuilder builder,
      ExpoModuleModel module,
      ExpoPropertyModel property,
      SharedObjectHostTarget? shared = null)
  {
    var setterName = shared?.HostFunctionName ?? GetPropertySetterFunctionName(module, property);
    var label = shared?.Label ?? module.ModuleName;
    var targetDeclaration = shared is null
        ? $"var module = ({module.FullyQualifiedTypeName})context;"
        : $"var module = SharedObjectCodec<{shared.ReceiverTypeName}>.Decode(thisValue, runtime, GeneratedFunction.CurrentRuntimeContext);";

    builder.AppendLine();
    builder.AppendLine($"  private static global::Expo.JSI.JavaScriptValue {setterName}(");
    builder.AppendLine("      global::Expo.JSI.JavaScriptRuntime runtime,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptValueRef thisValue,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptArguments arguments,");
    builder.AppendLine("      object context)");
    builder.AppendLine("  {");
    builder.AppendLine($"    GeneratedFunction.RequireArgumentCount(\"{EscapeString(label)}.{EscapeString(property.JavaScriptName)}\", arguments, 1);");
    builder.AppendLine($"    {targetDeclaration}");
    var decode = GetDecodeExpression(
        property.CodecExpression,
        0,
        "runtime",
        property.RequiresRuntimeContext
    );
    builder.AppendLine(property.OwnsDecodedValue
        ? $"    using var __expoValue = {decode};"
        : $"    var __expoValue = {decode};");
    builder.AppendLine($"    module.{property.PropertyName} = __expoValue;");
    builder.AppendLine("    return runtime.CreateUndefined();");
    builder.AppendLine("  }");
  }

  private static void EmitSpanHostFunction(
      StringBuilder builder,
      ExpoModuleModel module,
      ExpoFunctionModel function,
      SharedObjectHostTarget? shared = null)
  {
    var spanHostFunctionName = shared?.HostFunctionName ?? GetHostFunctionName(module, function);
    var spanLabel = shared?.Label ?? module.ModuleName;
    var spanTargetDeclaration = shared is null
        ? $"var module = ({module.FullyQualifiedTypeName})context;"
        : $"var module = SharedObjectCodec<{shared.ReceiverTypeName}>.Decode(thisValue, runtime, GeneratedFunction.CurrentRuntimeContext);";
    var spanParameter = function.Parameters.Values.Single(parameter =>
        parameter.PassingKind != ExpoParameterPassingKind.Codec);
    var spanIndex = Enumerable.Range(0, function.Parameters.Values.Count)
        .Single(index => ReferenceEquals(function.Parameters.Values[index], spanParameter));
    var spanBuffer = $"__expoSpanBuffer{spanIndex}";
    var spanMethod = spanParameter.PassingKind == ExpoParameterPassingKind.MutableByteSpan
        ? "WithBytes"
        : "WithReadOnlyBytes";

    builder.AppendLine();
    builder.AppendLine($"  private static global::Expo.JSI.JavaScriptValue {spanHostFunctionName}(");
    builder.AppendLine("      global::Expo.JSI.JavaScriptRuntime runtime,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptValueRef thisValue,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptArguments arguments,");
    builder.AppendLine("      object context)");
    builder.AppendLine("  {");
    builder.AppendLine($"    GeneratedFunction.RequireArgumentCount(\"{EscapeString(spanLabel)}.{EscapeString(function.JavaScriptName)}\", arguments, {GetRequiredParameterCount(function)}, {function.Parameters.Values.Count});");
    builder.AppendLine($"    {spanTargetDeclaration}");
    for (var index = 0; index < function.Parameters.Values.Count; index++)
    {
      var parameter = function.Parameters.Values[index];
      if (parameter.PassingKind != ExpoParameterPassingKind.Codec)
      {
        continue;
      }
      var declaration = parameter.OwnsDecodedValue ? "using var" : "var";
      builder.AppendLine($"    {declaration} {GetParameterLocalName(index)} = {GetParameterExpression(parameter, index, "runtime")};");
    }
    builder.AppendLine($"    using var {spanBuffer} = ArrayBufferCodec.Decode(arguments.GetValue({spanIndex}), runtime);");
    builder.AppendLine($"    return {spanBuffer}.{spanMethod}(__expoArg{spanIndex} =>");
    builder.AppendLine("    {");
    var argumentList = string.Join(", ", function.Parameters.Values.Select((_, index) => GetParameterLocalName(index)));
    var invocation = $"module.{function.MethodName}({argumentList})";
    if (function.ReturnsVoid)
    {
      builder.AppendLine($"      {invocation};");
      builder.AppendLine("      return runtime.CreateUndefined();");
    }
    else if (function.ReturnPassingKind != ExpoReturnPassingKind.Codec)
    {
      builder.AppendLine($"      return ArrayBufferCodec.EncodeCopy({invocation}, runtime);");
    }
    else if (function.ReturnCodecExpression == "ArrayBufferCodec")
    {
      builder.AppendLine($"      using var __expoResult = {invocation};");
      builder.AppendLine("      return ArrayBufferCodec.Encode(__expoResult, runtime);");
    }
    else if (function.ReturnCodecExpression == "JavaScriptValueCodec")
    {
      builder.AppendLine($"      return JavaScriptValueCodec.Encode({invocation}, runtime);");
    }
    else
    {
      builder.AppendLine($"      return {function.ReturnCodecExpression}.Encode({invocation}, runtime);");
    }
    builder.AppendLine("    });");
    builder.AppendLine("  }");
  }

  private static void EmitObservingHookFunction(
      StringBuilder builder,
      ExpoModuleModel module,
      string javaScriptName,
      IReadOnlyList<ExpoObservingHookModel> hooks)
  {
    builder.AppendLine();
    builder.AppendLine($"  private static global::Expo.JSI.JavaScriptValue {GetObservingHookFunctionName(module, javaScriptName)}(");
    builder.AppendLine("      global::Expo.JSI.JavaScriptRuntime runtime,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptValueRef thisValue,");
    builder.AppendLine("      global::Expo.JSI.JavaScriptArguments arguments,");
    builder.AppendLine("      object context)");
    builder.AppendLine("  {");
    builder.AppendLine($"    GeneratedFunction.RequireArgumentCount(\"{EscapeString(module.ModuleName)}.{javaScriptName}\", arguments, 1);");
    builder.AppendLine();
    builder.AppendLine($"    var module = ({module.FullyQualifiedTypeName})context;");
    builder.AppendLine("    var __expoEventName = StringCodec.Decode(arguments.GetValue(0), runtime);");
    foreach (var hook in hooks)
    {
      if (hook.EventName is not null)
      {
        builder.AppendLine($"    if (__expoEventName == \"{EscapeString(hook.EventName)}\")");
        builder.AppendLine("    {");
        builder.AppendLine($"      module.{hook.MethodName}();");
        builder.AppendLine("    }");
      }
      else
      {
        builder.AppendLine($"    module.{hook.MethodName}(__expoEventName);");
      }
    }
    builder.AppendLine("    return runtime.CreateUndefined();");
    builder.AppendLine("  }");
  }

  private static void EmitDisposeDecodedValues(
      StringBuilder builder,
      ExpoFunctionModel function,
      string indent)
  {
    for (var index = 0; index < function.Parameters.Values.Count; index++)
    {
      if (function.Parameters.Values[index].OwnsDecodedValue)
      {
        builder.AppendLine($"{indent}{GetParameterLocalName(index)}?.Dispose();");
      }
    }
  }

  private static void EmitRecordCodec(StringBuilder builder, ExpoGeneratedRecordCodecModel codec)
  {
    builder.AppendLine($"  private readonly struct {codec.CodecTypeName} : global::Expo.ModulesCore.Codecs.IJavaScriptCodec<{codec.RecordTypeName}>");
    builder.AppendLine("  {");
    builder.AppendLine($"    public static {codec.RecordTypeName} Decode(global::Expo.JSI.JavaScriptValueRef value, global::Expo.JSI.JavaScriptRuntime runtime)");
    builder.AppendLine("    {");
    builder.AppendLine("      var obj = value.AsObject();");
    foreach (var field in codec.Fields.Values)
    {
      builder.AppendLine($"      var {GetRecordFieldLocalName(field)} = {field.CodecExpression}.Decode(obj.GetProperty(\"{EscapeString(field.JavaScriptName)}\"), runtime);");
    }
    builder.AppendLine($"      return new {codec.RecordTypeName}({string.Join(", ", codec.Fields.Values.Select(GetRecordFieldLocalName))});");
    builder.AppendLine("    }");
    builder.AppendLine();
    builder.AppendLine($"    public static {codec.RecordTypeName} Decode(global::Expo.JSI.JavaScriptValue value, global::Expo.JSI.JavaScriptRuntime runtime)");
    builder.AppendLine("    {");
    builder.AppendLine("      using var obj = value.AsObject();");
    foreach (var field in codec.Fields.Values)
    {
      builder.AppendLine($"      using var {field.ParameterName}Value = obj.GetProperty(\"{EscapeString(field.JavaScriptName)}\");");
      builder.AppendLine($"      var {GetRecordFieldLocalName(field)} = {field.CodecExpression}.Decode({field.ParameterName}Value, runtime);");
    }
    builder.AppendLine($"      return new {codec.RecordTypeName}({string.Join(", ", codec.Fields.Values.Select(GetRecordFieldLocalName))});");
    builder.AppendLine("    }");
    builder.AppendLine();
    builder.AppendLine($"    public static global::Expo.JSI.JavaScriptValue Encode({codec.RecordTypeName} value, global::Expo.JSI.JavaScriptRuntime runtime)");
    builder.AppendLine("    {");
    builder.AppendLine("      using var obj = runtime.CreateObject();");
    foreach (var field in codec.Fields.Values)
    {
      builder.AppendLine($"      using var {GetRecordFieldLocalName(field)} = {field.CodecExpression}.Encode(value.{field.CSharpPropertyName}, runtime);");
      builder.AppendLine($"      obj.SetProperty(\"{EscapeString(field.JavaScriptName)}\", {GetRecordFieldLocalName(field)});");
    }
    builder.AppendLine("      return obj.AsValue();");
    builder.AppendLine("    }");
    builder.AppendLine("  }");
    builder.AppendLine();
  }

  private static string SanitizeIdentifier(string value)
  {
    var builder = new StringBuilder(value.Length);
    foreach (var character in value)
    {
      builder.Append(char.IsLetterOrDigit(character) ? character : '_');
    }
    return builder.Length == 0 ? "ExpoModules" : builder.ToString();
  }

  private static string GetHostFunctionName(ExpoModuleModel module, ExpoFunctionModel function) =>
      $"{SanitizeIdentifier(module.ModuleName)}_{SanitizeIdentifier(function.JavaScriptName)}_HostFunction";

  private static string GetPropertyGetterFunctionName(ExpoModuleModel module, ExpoPropertyModel property) =>
      $"{SanitizeIdentifier(module.ModuleName)}_{SanitizeIdentifier(property.PropertyName)}_Getter";

  private static string GetPropertySetterFunctionName(ExpoModuleModel module, ExpoPropertyModel property) =>
      $"{SanitizeIdentifier(module.ModuleName)}_{SanitizeIdentifier(property.PropertyName)}_Setter";

  private static string GetModuleRegistrationFunctionName(ExpoModuleModel module) =>
      $"Register{SanitizeIdentifier(module.ModuleName)}";

  private static string GetObservingHookFunctionName(ExpoModuleModel module, string javaScriptName) =>
      $"{SanitizeIdentifier(module.ModuleName)}_{SanitizeIdentifier(javaScriptName)}_HostFunction";

  private static string GetRecordFieldLocalName(ExpoGeneratedRecordFieldModel field) =>
      field.ParameterName == "value" ? "__expoValue" : field.ParameterName;

  private static int GetRequiredParameterCount(ExpoFunctionModel function) =>
      function.Parameters.Values.Count(parameter => !parameter.HasDefaultValue);

  private static string GetParameterLocalName(int index) =>
      $"__expoArg{index.ToString(CultureInfo.InvariantCulture)}";

}
