using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Expo.ModulesCore.Generator;

public sealed partial class ExpoModulesGenerator
{
  private static IEnumerable<string> GetEventNames(
      INamedTypeSymbol typeSymbol,
      string moduleName,
      List<ExpoDiagnosticModel> diagnostics)
  {
    var eventAttribute = typeSymbol.GetAttributes().FirstOrDefault(attribute =>
        attribute.AttributeClass?.ToDisplayString() == EventsAttributeMetadataName);
    if (eventAttribute is null)
    {
      return [];
    }

    var eventNames = new List<string>();
    var seen = new HashSet<string>(StringComparer.Ordinal);
    foreach (var argument in eventAttribute.ConstructorArguments)
    {
      foreach (var value in GetEventNameValues(argument))
      {
        if (string.IsNullOrWhiteSpace(value))
        {
          diagnostics.Add(new ExpoDiagnosticModel(
              ExpoModulesDiagnostics.InvalidEventName.Id,
              typeSymbol.Locations.FirstOrDefault(),
              new EquatableArray<string>(new[] { moduleName, "empty", value ?? string.Empty })
          ));
          continue;
        }

        var eventName = value!;
        if (!seen.Add(eventName))
        {
          diagnostics.Add(new ExpoDiagnosticModel(
              ExpoModulesDiagnostics.InvalidEventName.Id,
              typeSymbol.Locations.FirstOrDefault(),
              new EquatableArray<string>(new[] { moduleName, "duplicate", eventName })
          ));
          continue;
        }

        eventNames.Add(eventName);
      }
    }
    if (eventNames.Count == 0)
    {
      diagnostics.Add(new ExpoDiagnosticModel(
          ExpoModulesDiagnostics.InvalidEventName.Id,
          typeSymbol.Locations.FirstOrDefault(),
          new EquatableArray<string>(new[] { moduleName, "empty", string.Empty })
      ));
    }

    return eventNames;
  }

  private static IEnumerable<string?> GetEventNameValues(TypedConstant argument)
  {
    if (argument.Kind == TypedConstantKind.Array)
    {
      return argument.Values.Select(value => value.Value as string);
    }

    return new[] { argument.Value as string };
  }

  private static ExpoOrphanEventModel? CreateOrphanEventModel(
      GeneratorAttributeSyntaxContext context,
      CancellationToken cancellationToken)
  {
    cancellationToken.ThrowIfCancellationRequested();
    if (context.TargetSymbol is not IPropertySymbol property ||
        property.ContainingType is not INamedTypeSymbol type ||
        type.GetAttributes().Any(attribute =>
            attribute.AttributeClass?.ToDisplayString() is
                ExpoModuleAttributeMetadataName or ExpoSharedObjectAttributeMetadataName))
    {
      return null;
    }

    var declaration = context.TargetNode as PropertyDeclarationSyntax;
    var canReproduce = declaration is not null &&
        type.ContainingType is null &&
        !type.IsGenericType &&
        declaration.Modifiers.Any(SyntaxKind.PartialKeyword) &&
        property.GetMethod is not null &&
        property.SetMethod is null;
    return new ExpoOrphanEventModel(
        type.ContainingNamespace.IsGlobalNamespace ? string.Empty : type.ContainingNamespace.ToDisplayString(),
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
        type.Name,
        GetAccessibilityText(type.DeclaredAccessibility),
        property.Name,
        property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
        declaration is null ? "public partial" : GetEventDeclarationModifiers(declaration, property),
        declaration is null ? "get" : GetEventAccessorText(declaration, SyntaxKind.GetAccessorDeclaration),
        property.Locations.FirstOrDefault(),
        canReproduce
    );
  }

  private static void EmitOrphanEvent(
      SourceProductionContext context,
      ExpoOrphanEventModel model)
  {
    context.ReportDiagnostic(Diagnostic.Create(
        ExpoModulesDiagnostics.UnsupportedSharedObjectEventProperty,
        model.Location,
        model.ContainerName,
        model.PropertyName,
        "declared on a class that is neither an Expo module nor an Expo shared object"
    ));
    if (!model.CanReproduce) return;
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated/>");
    builder.AppendLine("#nullable enable");
    if (model.Namespace.Length > 0)
    {
      builder.AppendLine($"namespace {model.Namespace};");
      builder.AppendLine();
    }
    builder.AppendLine($"{model.ContainerAccessibility} partial class {EscapeIdentifier(model.ContainerName)}");
    builder.AppendLine("{");
    builder.AppendLine($"  {model.PropertyModifiers} {model.PropertyType} {EscapeIdentifier(model.PropertyName)}");
    builder.AppendLine("  {");
    builder.AppendLine($"    {model.GetterAccessor} => throw new global::System.InvalidOperationException(\"Event member '{model.ContainerName}.{model.PropertyName}' is not declared on an Expo event target.\");");
    builder.AppendLine("  }");
    builder.AppendLine("}");
    context.AddSource(
        $"{SanitizeIdentifier(model.FullyQualifiedContainerName)}_{GetStableHash(model.FullyQualifiedContainerName + model.PropertyName):X8}.OrphanEvent.g.cs",
        SourceText.From(builder.ToString(), Encoding.UTF8)
    );
  }

  private static List<ExpoEventModel> GetTypedEvents(
      INamedTypeSymbol typeSymbol,
      string moduleName,
      List<ExpoDiagnosticModel> diagnostics,
      List<ExpoGeneratedRecordCodecModel> recordCodecs,
      string unsupportedPropertyDiagnosticId = "EXPOJSI018",
      string unsupportedPayloadDiagnosticId = "EXPOJSI019",
      string? containerReasonOverride = null)
  {
    var events = new List<ExpoEventModel>();
    var unsupportedContainerShape = GetUnsupportedEventContainerShape(typeSymbol);
    var containerReason = containerReasonOverride ?? unsupportedContainerShape;
    foreach (var property in typeSymbol.GetMembers().OfType<IPropertySymbol>()
                 .OrderBy(member => member.Locations.FirstOrDefault()?.SourceSpan.Start ?? int.MaxValue))
    {
      var eventAttribute = property.GetAttributes().FirstOrDefault(attribute =>
          attribute.AttributeClass?.ToDisplayString() == EventAttributeMetadataName);
      if (eventAttribute is null)
      {
        continue;
      }

      var declaration = property.DeclaringSyntaxReferences
          .Select(reference => reference.GetSyntax())
          .OfType<PropertyDeclarationSyntax>()
          .FirstOrDefault();
      var propertyReason = containerReason ?? GetUnsupportedEventPropertyShape(property, declaration);
      var canReproduce = unsupportedContainerShape is null &&
          CanReproduceEventProperty(property, declaration);
      var javaScriptName = LowerCamel(property.Name);
      ITypeSymbol? payloadType = null;
      var hasUnsupportedPayload = false;
      if (eventAttribute.ConstructorArguments.Length == 1)
      {
        var explicitName = eventAttribute.ConstructorArguments[0].Value as string;
        if (string.IsNullOrWhiteSpace(explicitName))
        {
          propertyReason ??= explicitName is null ? "a null explicit name" : "an empty or blank explicit name";
        }
        else
        {
          javaScriptName = explicitName!;
        }
      }

      var payloadKind = ExpoEventPayloadKind.None;
      var payloadTypeName = string.Empty;
      var codecExpression = string.Empty;
      if (propertyReason is null && !TryGetEventDelegatePayload(
              property.Type,
              out payloadType,
              out payloadKind,
              out var delegateReason))
      {
        propertyReason = delegateReason;
      }

      if (payloadType is not null)
      {
        payloadTypeName = payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
      }

      if (propertyReason is null && payloadType is not null && payloadKind == ExpoEventPayloadKind.Codec)
      {
        var payloadReason = GetUnsupportedEventPayload(payloadType);
        if (payloadReason is not null)
        {
          diagnostics.Add(CreateUnsupportedEventPayload(
              moduleName, property, payloadType, payloadReason, unsupportedPayloadDiagnosticId));
          hasUnsupportedPayload = true;
          propertyReason = "an unsupported payload";
        }
        else
        {
          var scratchRecordCodecs = recordCodecs.ToList();
          var scratchDiagnostics = new List<ExpoDiagnosticModel>();
          codecExpression = GetCodecExpression(payloadType, scratchDiagnostics, scratchRecordCodecs) ?? string.Empty;
          if (codecExpression.Length == 0)
          {
            diagnostics.Add(CreateUnsupportedEventPayload(
                moduleName,
                property,
                payloadType,
                "no encode-capable codec is available",
                unsupportedPayloadDiagnosticId
            ));
            hasUnsupportedPayload = true;
            propertyReason = "an unsupported payload";
          }
          else
          {
            recordCodecs.Clear();
            recordCodecs.AddRange(scratchRecordCodecs);
          }
        }
      }
      else if (propertyReason is null && payloadType is not null)
      {
        var payloadReason = GetUnsupportedEventPayload(payloadType);
        if (payloadReason is not null)
        {
          diagnostics.Add(CreateUnsupportedEventPayload(
              moduleName, property, payloadType, payloadReason, unsupportedPayloadDiagnosticId));
          hasUnsupportedPayload = true;
          propertyReason = "an unsupported payload";
        }
      }

      if (propertyReason is not null && !hasUnsupportedPayload)
      {
        diagnostics.Add(new ExpoDiagnosticModel(
            unsupportedPropertyDiagnosticId,
            property.Locations.FirstOrDefault(),
            new EquatableArray<string>(new[] { moduleName, property.Name, propertyReason })
        ));
      }

      events.Add(new ExpoEventModel(
          property.Name,
          javaScriptName,
          GetAccessibilityText(property.DeclaredAccessibility),
          GetEventDeclarationModifiers(declaration, property),
          GetEventAccessorText(declaration, SyntaxKind.GetAccessorDeclaration),
          GetEventAccessorText(declaration, SyntaxKind.SetAccessorDeclaration, SyntaxKind.InitAccessorDeclaration),
          property.IsStatic,
          property.SetMethod is not null,
          property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
          payloadTypeName,
          payloadKind,
          codecExpression,
          property.Locations.FirstOrDefault(),
          canReproduce,
          propertyReason is null
      ));
    }

    return events;
  }

  private static IReadOnlyList<string> MergeEventNames(
      string moduleName,
      List<string> legacyEventNames,
      List<ExpoEventModel> typedEvents,
      List<ExpoDiagnosticModel> diagnostics)
  {
    var names = new List<string>(legacyEventNames);
    var seen = new HashSet<string>(legacyEventNames, StringComparer.Ordinal);
    for (var index = 0; index < typedEvents.Count; index++)
    {
      var typedEvent = typedEvents[index];
      if (!typedEvent.IsDispatchable)
      {
        continue;
      }
      if (!seen.Add(typedEvent.JavaScriptName))
      {
        diagnostics.Add(new ExpoDiagnosticModel(
            ExpoModulesDiagnostics.DuplicateEventName.Id,
            typedEvent.Location,
            new EquatableArray<string>(new[] { moduleName, typedEvent.PropertyName, typedEvent.JavaScriptName })
        ));
        typedEvents[index] = typedEvent with { IsDispatchable = false };
        continue;
      }
      names.Add(typedEvent.JavaScriptName);
    }
    return names;
  }

  private static ExpoDiagnosticModel CreateUnsupportedEventPayload(
      string moduleName,
      IPropertySymbol property,
      ITypeSymbol payloadType,
      string reason,
      string diagnosticId = "EXPOJSI019") =>
      new(
          diagnosticId,
          payloadType.Locations.FirstOrDefault() ?? property.Locations.FirstOrDefault(),
          new EquatableArray<string>(new[] { moduleName, property.Name, GetDiagnosticTypeName(payloadType), reason })
      );

  private static bool TryGetEventDelegatePayload(
      ITypeSymbol delegateType,
      out ITypeSymbol? payloadType,
      out ExpoEventPayloadKind payloadKind,
      out string reason)
  {
    payloadType = null;
    payloadKind = ExpoEventPayloadKind.None;
    reason = "a non-awaitable delegate; events must use Func<Task> or Func<T, Task>";
    if (delegateType is not INamedTypeSymbol namedDelegate ||
        namedDelegate.DelegateInvokeMethod is null)
    {
      return false;
    }

    var definition = namedDelegate.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    if (definition == "global::System.Func<TResult>" &&
        IsTaskType(namedDelegate.TypeArguments.Single()))
    {
      return true;
    }
    if (definition == "global::System.Func<T, TResult>" &&
        IsTaskType(namedDelegate.TypeArguments[1]))
    {
      payloadType = namedDelegate.TypeArguments[0];
      var payloadName = payloadType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
      payloadKind = payloadName == JavaScriptValueMetadataName
          ? ExpoEventPayloadKind.JavaScriptValue
          : payloadName == ArrayBufferMetadataName
              ? ExpoEventPayloadKind.ArrayBuffer
              : ExpoEventPayloadKind.Codec;
      return true;
    }
    return false;
  }

  private static bool IsTaskType(ITypeSymbol typeSymbol) =>
      typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
      "global::System.Threading.Tasks.Task";

  private static string? GetUnsupportedEventPayload(ITypeSymbol payloadType) =>
      GetUnsupportedEventPayload(payloadType, true, new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default));

  private static string? GetUnsupportedEventPayload(
      ITypeSymbol typeSymbol,
      bool isTopLevel,
      HashSet<ITypeSymbol> visitedTypes)
  {
    if (!visitedTypes.Add(typeSymbol))
    {
      return "it contains a recursive record codec";
    }
    try
    {
      if (IsJavaScriptCallbackType(typeSymbol)) return "it contains JavaScriptCallback, which is decode-only";
      var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
      if (typeName is JavaScriptValueMetadataName or ArrayBufferMetadataName)
        return isTopLevel ? null : "it contains a nested transfer-sensitive wrapper";
      if (typeSymbol is not INamedTypeSymbol namedType) return null;
      if (namedType.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        return GetUnsupportedEventPayload(namedType.TypeArguments.Single(), false, visitedTypes);
      if (namedType.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
          "global::System.Collections.Generic.IReadOnlyList<T>")
        return GetUnsupportedEventPayload(namedType.TypeArguments.Single(), false, visitedTypes);
      var definition = namedType.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
      if (definition is "global::System.Collections.Generic.Dictionary<TKey, TValue>" or
          "global::System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>")
        return namedType.TypeArguments[0].SpecialType == SpecialType.System_String
            ? GetUnsupportedEventPayload(namedType.TypeArguments[1], false, visitedTypes)
            : null;
      if (!namedType.IsRecord) return null;
      var constructor = GetRecordCodecConstructor(namedType);
      return constructor is null
          ? null
          : constructor.Parameters.Select(parameter => GetUnsupportedEventPayload(parameter.Type, false, visitedTypes))
              .FirstOrDefault(reason => reason is not null);
    }
    finally
    {
      visitedTypes.Remove(typeSymbol);
    }
  }

  private static string? GetUnsupportedEventContainerShape(INamedTypeSymbol typeSymbol)
  {
    if (typeSymbol.ContainingType is not null) return "declared in a nested module container";
    if (typeSymbol.TypeParameters.Length != 0) return "declared in a generic module container";
    if (typeSymbol.DeclaringSyntaxReferences.Any(reference =>
            reference.GetSyntax() is TypeDeclarationSyntax declaration &&
            declaration.Modifiers.Any(SyntaxKind.FileKeyword)))
    {
      return "declared in a file-local module container";
    }
    if (typeSymbol.DeclaringSyntaxReferences.Any(reference =>
            reference.GetSyntax() is TypeDeclarationSyntax declaration &&
            !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)))
    {
      return "declared in a non-partial module container";
    }
    return null;
  }

  private static string? GetUnsupportedEventPropertyShape(
      IPropertySymbol property,
      PropertyDeclarationSyntax? declaration)
  {
    if (property.IsStatic) return "static";
    if (property.IsIndexer) return "indexed";
    if (property.ExplicitInterfaceImplementations.Length != 0 || declaration?.ExplicitInterfaceSpecifier is not null)
      return "an explicit-interface property";
    if (property.RefKind != RefKind.None) return "a ref-return property";
    if (declaration is null || !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)) return "non-partial";
    if (property.SetMethod is not null) return "a setter";
    if (HasAuthoredPartialImplementation(property)) return "an authored implementation";
    if (declaration.ExpressionBody is not null || declaration.AccessorList?.Accessors.Any(accessor =>
            accessor.Body is not null || accessor.ExpressionBody is not null) == true)
      return "an authored implementation";
    if (property.GetMethod is null) return "getter-less";
    if (property.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
      return "not public or internal";
    foreach (var modifier in declaration.Modifiers)
    {
      if (modifier.IsKind(SyntaxKind.PartialKeyword) ||
          modifier.IsKind(SyntaxKind.PublicKeyword) ||
          modifier.IsKind(SyntaxKind.InternalKeyword))
      {
        continue;
      }
      return $"modified with '{modifier.Text}'";
    }
    if (property.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == JSAttributeMetadataName))
      return "also marked [JS]";
    return null;
  }

  private static bool CanReproduceEventProperty(
      IPropertySymbol property,
      PropertyDeclarationSyntax? declaration)
  {
    if (HasAuthoredPartialImplementation(property) ||
        property.IsIndexer ||
        property.ExplicitInterfaceImplementations.Length != 0 ||
        property.RefKind != RefKind.None ||
        declaration is null ||
        !declaration.Modifiers.Any(SyntaxKind.PartialKeyword) ||
        declaration.ExpressionBody is not null ||
        declaration.AccessorList?.Accessors.Any(accessor =>
            accessor.Body is not null || accessor.ExpressionBody is not null) != false)
    {
      return false;
    }

    return !declaration.Modifiers.Any(modifier =>
        modifier.IsKind(SyntaxKind.AbstractKeyword) || modifier.IsKind(SyntaxKind.ExternKeyword));
  }

  private static bool HasAuthoredPartialImplementation(IPropertySymbol property) =>
      property.PartialImplementationPart is not null ||
      property.PartialDefinitionPart?.PartialImplementationPart is not null;

  private static string GetEventDeclarationModifiers(
      PropertyDeclarationSyntax? declaration,
      IPropertySymbol property) => declaration is null
      ? $"{GetAccessibilityText(property.DeclaredAccessibility)} partial"
      : string.Join(" ", declaration.Modifiers.Select(modifier => modifier.Text));

  private static string GetEventAccessorText(
      PropertyDeclarationSyntax? declaration,
      params SyntaxKind[] kinds)
  {
    var accessor = declaration?.AccessorList?.Accessors.FirstOrDefault(item => kinds.Contains(item.Kind()));
    return accessor is null
        ? string.Empty
        : string.Join(" ", accessor.Modifiers.Select(modifier => modifier.Text).Append(accessor.Keyword.Text));
  }

  private static string GetAccessibilityText(Accessibility accessibility) => accessibility switch
  {
    Accessibility.Public => "public",
    Accessibility.Internal => "internal",
    Accessibility.Private => "private",
    Accessibility.Protected => "protected",
    Accessibility.ProtectedOrInternal => "protected internal",
    Accessibility.ProtectedAndInternal => "private protected",
    _ => "private",
  };


}
