import * as path from 'path';

import type { DotnetLinkingManifest, DotnetProjectRef } from '../types';
import { writeIfChangedSync } from './writeIfChanged';

const csharpBanner = '// Automatically generated by expo-modules-dotnet-autolinking. Do not edit.';
const xmlBanner = '<!-- Automatically generated by expo-modules-dotnet-autolinking. Do not edit. -->';

export interface GenerateOptions {
  outputDir: string;
  adapterPackageRoot: string;
}

export interface GenerateResult {
  writtenFiles: string[];
  skippedFiles: string[];
}

export function generateAggregator(
  manifest: DotnetLinkingManifest,
  options: GenerateOptions
): GenerateResult {
  const projects = manifest.modules.flatMap((module) => module.projects);
  const files = [
    {
      fileName: 'ExpoDotnetHost.csproj',
      content: generateCsproj(projects, options),
    },
    {
      fileName: 'LinkedExpoModulesProvider.g.cs',
      content: generateLinkedProvider(projects),
    },
    {
      fileName: 'EntryPoints.g.cs',
      content: generateEntryPoints(),
    },
  ];
  const result: GenerateResult = { writtenFiles: [], skippedFiles: [] };

  for (const file of files) {
    const filePath = path.join(options.outputDir, file.fileName);
    if (writeIfChangedSync(filePath, file.content)) {
      result.writtenFiles.push(filePath);
    } else {
      result.skippedFiles.push(filePath);
    }
  }

  return result;
}

function generateCsproj(projects: DotnetProjectRef[], options: GenerateOptions): string {
  const coreReferences = [
    path.join(options.adapterPackageRoot, 'managed/packages/Expo.JSI/Expo.JSI.csproj'),
    path.join(
      options.adapterPackageRoot,
      'managed/packages/Expo.ModulesCore/Expo.ModulesCore.csproj'
    ),
  ];
  const projectReferences = [...coreReferences, ...projects.map((project) => project.csprojPath)]
    .map((target) => relativePath(options.outputDir, target))
    .map((target) => `    <ProjectReference Include="${escapeXmlAttribute(target)}" />`)
    .join('\n');

  return `${xmlBanner}
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AssemblyName>ExpoDotnetHost</AssemblyName>
    <RootNamespace>Expo.ModulesCore.Generated</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <PropertyGroup Condition="'$(PublishAot)' == 'true'">
    <NativeLib>Shared</NativeLib>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="LinkedExpoModulesProvider.g.cs" />
    <Compile Include="EntryPoints.g.cs" />
  </ItemGroup>
  <ItemGroup>
${projectReferences}
  </ItemGroup>
</Project>
`;
}

// Mirrors SanitizeIdentifier in Expo.ModulesCore.Generator/ExpoModulesGenerator.cs —
// the Roslyn generator derives the provider type name from the assembly name the same way.
function sanitizeIdentifier(value: string): string {
  const sanitized = value.replace(/[^\p{L}\p{Nd}]/gu, '_');
  return sanitized.length === 0 ? 'ExpoModules' : sanitized;
}

function generateLinkedProvider(projects: DotnetProjectRef[]): string {
  const registrations = projects
    .map(
      (project) =>
        `        Expo.ModulesCore.Generated.ExpoModulesProvider_${sanitizeIdentifier(project.assemblyName)}.Register(context);`
    )
    .join('\n');
  const body = registrations.length > 0 ? `${registrations}\n` : '';

  return `${csharpBanner}
using Expo.ModulesCore;

namespace Expo.ModulesCore.Generated;

public static class LinkedExpoModulesProvider
{
    public static void Register(DotnetRuntimeContext context)
    {
${body}    }
}
`;
}

function generateEntryPoints(): string {
  return `${csharpBanner}
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using Expo.JSI;
using Expo.ModulesCore;

namespace Expo.ModulesCore.Generated;

// Partial so the autolinking ABI harness fixture, compiled into the same
// assembly, can exercise the private app-directories decoder without widening
// its visibility in a shipped app.
public static partial class EntryPoints
{
    private const uint ExpectedHostAbiVersion = 1;

    // Strict decoding, matching Expo.JSI: an invalid UTF-8 host path is a bug to
    // report, never something to silently repair with replacement characters.
    private static readonly UTF8Encoding StrictUtf8 = new(false, true);

    [UnmanagedCallersOnly(
        EntryPoint = "expo_dotnet_create_runtime_context_result_v2",
        CallConvs = new[] { typeof(CallConvCdecl) }
    )]
    public static unsafe void CreateRuntimeContextResultV2(
        nint api,
        nint runtimeHandle,
        nint appDirectories,
        RuntimeContextResult* result)
    {
        if (result is null)
        {
            return;
        }

        try
        {
            var context = CreateRuntimeContextCore(api, runtimeHandle, appDirectories);
            result->Ok = 1;
            result->RuntimeContext = context;
            result->Error = default;
        }
        catch (Exception ex)
        {
            SetError(result, ex);
            LogException(ex);
        }
    }

    [UnmanagedCallersOnly(
        EntryPoint = "expo_dotnet_teardown_runtime_context",
        CallConvs = new[] { typeof(CallConvCdecl) }
    )]
    public static void TeardownRuntimeContext(nint runtimeContext)
    {
        try
        {
            TeardownRuntimeContextCore(runtimeContext);
        }
        catch (Exception ex)
        {
            LogException(ex);
        }
    }

    private static unsafe nint CreateRuntimeContextCore(
        nint api,
        nint runtimeHandle,
        nint appDirectories)
    {
        // Decode first: the directories must be present before
        // LinkedExpoModulesProvider.Register runs, because a module constructor
        // can already observe the context there.
        var directories = DecodeAppDirectories(appDirectories);
        var runtime = JavaScriptRuntime.FromNative(api, runtimeHandle);
        var context = new DotnetRuntimeContext(runtime, directories);
        try
        {
            LinkedExpoModulesProvider.Register(context);
            return GCHandle.ToIntPtr(GCHandle.Alloc(context));
        }
        catch
        {
            DisposeRuntimeContext(context);
            throw;
        }
    }

    // Startup cleanup and app teardown run behind unmanaged entry points. Keep
    // every exception contained so managed failures never cross the C ABI.
    private static void TeardownRuntimeContextCore(nint runtimeContext)
    {
        if (runtimeContext == 0)
        {
            return;
        }

        var handle = GCHandle.FromIntPtr(runtimeContext);
        try
        {
            if (handle.Target is DotnetRuntimeContext context)
            {
                DisposeRuntimeContext(context);
            }
        }
        finally
        {
            // The native adapter passed this opaque context back to us; release
            // its GCHandle even when managed context disposal reports failures.
            handle.Free();
        }
    }

    private static void DisposeRuntimeContext(DotnetRuntimeContext context)
    {
        try
        {
            context.Dispose();
        }
        catch (Exception ex)
        {
            LogException(ex);
        }
    }

    private static void LogException(Exception exception)
    {
        try
        {
            Console.Error.WriteLine(exception);
        }
        catch
        {
            // Best-effort logging only. Throwing while reporting an exception
            // would reopen the unmanaged boundary this path is protecting.
        }
    }

    private static unsafe void SetError(RuntimeContextResult* result, Exception exception)
    {
        var message = Encoding.UTF8.GetBytes(exception.Message);
        var buffer = Marshal.AllocHGlobal(message.Length);
        Marshal.Copy(message, 0, buffer, message.Length);

        result->Ok = 0;
        result->RuntimeContext = 0;
        result->Error.Message = (byte*)buffer;
        result->Error.MessageLength = message.Length;
        result->Error.ReleaseContext = buffer;
        result->Error.Release = &ReleaseRuntimeContextError;
    }

    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static void ReleaseRuntimeContextError(nint releaseContext)
    {
        if (releaseContext != 0)
        {
            Marshal.FreeHGlobal(releaseContext);
        }
    }

    // Mirrors expo_dotnet_app_directories in
    // expo-modules-dotnet/native/include/expo_dotnet_host.h. The field order and
    // types must match that header exactly; the header carries static_assert
    // checks for its own layout, and the autolinking ABI harness asserts this
    // one.
    [StructLayout(LayoutKind.Sequential)]
    private unsafe struct NativeAppDirectories
    {
        public uint Size;
        public uint Version;
        public byte* CacheDirectory;
        public int CacheDirectoryLength;
        public byte* PersistentFilesDirectory;
        public int PersistentFilesDirectoryLength;
    }

    // A null struct pointer means the host configured neither directory. Size is
    // checked before Version, and both before any pointer field is read.
    private static unsafe AppDirectories DecodeAppDirectories(nint pointer)
    {
        if (pointer == 0)
        {
            return AppDirectories.Unconfigured;
        }

        var native = (NativeAppDirectories*)pointer;
        var expectedSize = (uint)sizeof(NativeAppDirectories);
        if (native->Size < expectedSize)
        {
            throw new InvalidOperationException(
                $"Expo .NET host app-directories struct is too small. Expected at least {expectedSize}, got {native->Size}."
            );
        }
        if (native->Version != ExpectedHostAbiVersion)
        {
            throw new InvalidOperationException(
                $"Expo .NET host ABI version mismatch: native={native->Version} managed={ExpectedHostAbiVersion}."
            );
        }

        return new AppDirectories(
            DecodeDirectory(native->CacheDirectory, native->CacheDirectoryLength, "cache_directory"),
            DecodeDirectory(
                native->PersistentFilesDirectory,
                native->PersistentFilesDirectoryLength,
                "persistent_files_directory"
            )
        );
    }

    // The strings are borrowed for the duration of the create call, so copy them
    // into managed strings here rather than holding the pointers.
    private static unsafe string? DecodeDirectory(byte* data, int length, string fieldName)
    {
        if (length < 0)
        {
            throw new InvalidOperationException($"{fieldName} has a negative byte length.");
        }
        if (data == null)
        {
            if (length == 0)
            {
                return null;
            }
            throw new InvalidOperationException($"{fieldName} has a byte length but no data.");
        }
        return StrictUtf8.GetString(new ReadOnlySpan<byte>(data, length));
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct RuntimeContextResult
    {
        public int Ok;
        public nint RuntimeContext;
        public RuntimeContextError Error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct RuntimeContextError
    {
        public byte* Message;
        public int MessageLength;
        public nint ReleaseContext;
        public delegate* unmanaged[Cdecl]<nint, void> Release;
    }
}
`;
}

function relativePath(from: string, to: string): string {
  return path.relative(from, to).split(path.sep).join('/');
}

function escapeXmlAttribute(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
