import * as path from 'path';

import type { DotnetLinkingManifest, DotnetProjectRef } from '../types';
import { writeIfChangedSync } from './writeIfChanged';

const csharpBanner = '// Automatically generated by expo-modules-dotnet-autolinking. Do not edit.';
const xmlBanner = '<!-- Automatically generated by expo-modules-dotnet-autolinking. Do not edit. -->';

export interface GenerateOptions {
  outputDir: string;
  adapterPackageRoot: string;
  platform?: string;
}

export interface GenerateResult {
  writtenFiles: string[];
  skippedFiles: string[];
}

export function generateAggregator(
  manifest: DotnetLinkingManifest,
  options: GenerateOptions
): GenerateResult {
  const projects = manifest.modules.flatMap((module) => module.projects);
  const files = [
    {
      fileName: 'ExpoDotnetHost.csproj',
      content: generateCsproj(projects, options),
    },
    {
      fileName: 'LinkedExpoModulesProvider.g.cs',
      content: generateLinkedProvider(projects),
    },
    {
      fileName: 'EntryPoints.g.cs',
      content: generateEntryPoints(options),
    },
  ];
  const result: GenerateResult = { writtenFiles: [], skippedFiles: [] };

  for (const file of files) {
    const filePath = path.join(options.outputDir, file.fileName);
    if (writeIfChangedSync(filePath, file.content)) {
      result.writtenFiles.push(filePath);
    } else {
      result.skippedFiles.push(filePath);
    }
  }

  return result;
}

function generateCsproj(projects: DotnetProjectRef[], options: GenerateOptions): string {
  const isWindows = options.platform === 'windows';
  const targetFramework = isWindows ? 'net10.0-windows10.0.19041.0' : 'net10.0';
  const coreReferences = [
    path.join(options.adapterPackageRoot, 'managed/packages/Expo.JSI/Expo.JSI.csproj'),
    path.join(
      options.adapterPackageRoot,
      'managed/packages/Expo.ModulesCore/Expo.ModulesCore.csproj'
    ),
    ...(isWindows
      ? [
          path.join(
            options.adapterPackageRoot,
            '..',
            'expo-modules-dotnet-windows',
            'managed/Expo.ModulesCore.Windows/Expo.ModulesCore.Windows.csproj'
          ),
        ]
      : []),
  ];
  const projectReferences = [...coreReferences, ...projects.map((project) => project.csprojPath)]
    .map((target) => relativePath(options.outputDir, target))
    .map((target) => `    <ProjectReference Include="${escapeXmlAttribute(target)}" />`)
    .join('\n');

  return `${xmlBanner}
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>${targetFramework}</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AssemblyName>ExpoDotnetHost</AssemblyName>
    <RootNamespace>Expo.ModulesCore.Generated</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <PropertyGroup Condition="'$(PublishAot)' == 'true'">
    <NativeLib>Shared</NativeLib>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="LinkedExpoModulesProvider.g.cs" />
    <Compile Include="EntryPoints.g.cs" />
  </ItemGroup>
  <ItemGroup>
${projectReferences}
  </ItemGroup>
</Project>
`;
}

// Mirrors SanitizeIdentifier in Expo.ModulesCore.Generator/ExpoModulesGenerator.cs —
// the Roslyn generator derives the provider type name from the assembly name the same way.
function sanitizeIdentifier(value: string): string {
  const sanitized = value.replace(/[^\p{L}\p{Nd}]/gu, '_');
  return sanitized.length === 0 ? 'ExpoModules' : sanitized;
}

function generateLinkedProvider(projects: DotnetProjectRef[]): string {
  const registrations = projects
    .map(
      (project) =>
        `        Expo.ModulesCore.Generated.ExpoModulesProvider_${sanitizeIdentifier(project.assemblyName)}.Register(context);`
    )
    .join('\n');
  const body = registrations.length > 0 ? `${registrations}\n` : '';
  const viewDefinitionRegistrations = projects
    .map(
      (project) =>
        `        views.AddRange(Expo.ModulesCore.Generated.ExpoModulesProvider_${sanitizeIdentifier(project.assemblyName)}.GetViewDefinitions());`
    )
    .join('\n');
  const viewDefinitionBody =
    viewDefinitionRegistrations.length > 0 ? `${viewDefinitionRegistrations}\n` : '';
  const createViewCases = projects
    .map((project) => {
      const provider = `Expo.ModulesCore.Generated.ExpoModulesProvider_${sanitizeIdentifier(project.assemblyName)}`;
      return `        if (${provider}.GetViewDefinitions().Any(view => view.ComponentName == componentName))
        {
            return ${provider}.CreateView(context, componentName);
        }`;
    })
    .join('\n');
  const updateViewCases = projects
    .map((project) => {
      const provider = `Expo.ModulesCore.Generated.ExpoModulesProvider_${sanitizeIdentifier(project.assemblyName)}`;
      return `        if (${provider}.GetViewDefinitions().Any(view => view.ComponentName == componentName))
        {
            ${provider}.UpdateViewProp(context, componentName, view, propName, value);
            return;
        }`;
    })
    .join('\n');

  return `${csharpBanner}
using System.Collections.Generic;
using System.Linq;
using Expo.ModulesCore;

namespace Expo.ModulesCore.Generated;

public static class LinkedExpoModulesProvider
{
    public static void Register(DotnetRuntimeContext context)
    {
${body}    }

    public static IReadOnlyList<GeneratedViewDefinition> GetViewDefinitions()
    {
        var views = new List<GeneratedViewDefinition>();
${viewDefinitionBody}        return views;
    }

    public static object CreateView(DotnetRuntimeContext context, string componentName)
    {
${createViewCases}
        throw new InvalidOperationException($"Unknown Expo view component '{componentName}'.");
    }

    public static void UpdateViewProp(
        DotnetRuntimeContext context,
        string componentName,
        object view,
        string propName,
        string? value)
    {
${updateViewCases}
    }
}
`;
}

function generateEntryPoints(options: GenerateOptions): string {
  const windowsViewEntryPoints =
    options.platform === 'windows'
      ? `
    [UnmanagedCallersOnly(
        EntryPoint = "expo_dotnet_windows_get_view_metadata",
        CallConvs = new[] { typeof(CallConvCdecl) }
    )]
    public static unsafe int GetWindowsViewMetadata(byte** outJson, int* outLength)
    {
        try
        {
            var metadata = LinkedExpoModulesProvider.GetViewDefinitions()
                .Select(view => new
                {
                    view.ModuleName,
                    view.ComponentName,
                    Props = view.Props.Select(prop => new { prop.Name, Kind = prop.Kind.ToString() }).ToArray(),
                })
                .ToArray();
            var bytes = System.Text.Encoding.UTF8.GetBytes(System.Text.Json.JsonSerializer.Serialize(metadata));
            var buffer = (byte*)NativeMemory.Alloc((nuint)bytes.Length);
            bytes.CopyTo(new Span<byte>(buffer, bytes.Length));
            *outJson = buffer;
            *outLength = bytes.Length;
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex);
            *outJson = null;
            *outLength = 0;
            return -1;
        }
    }

    [UnmanagedCallersOnly(
        EntryPoint = "expo_dotnet_windows_free_buffer",
        CallConvs = new[] { typeof(CallConvCdecl) }
    )]
    public static unsafe void FreeWindowsBuffer(byte* buffer)
    {
        if (buffer is not null)
        {
            NativeMemory.Free(buffer);
        }
    }

    [UnmanagedCallersOnly(
        EntryPoint = "expo_dotnet_windows_create_view",
        CallConvs = new[] { typeof(CallConvCdecl) }
    )]
    public static nint CreateWindowsView(nint runtimeContext, nint componentNameUtf8, int componentNameLength)
    {
        try
        {
            var context = RuntimeContextFromHandle(runtimeContext);
            var componentName = ReadUtf8(componentNameUtf8, componentNameLength);
            var view = LinkedExpoModulesProvider.CreateView(context, componentName);
            return GCHandle.ToIntPtr(GCHandle.Alloc(view));
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex);
            return 0;
        }
    }

    [UnmanagedCallersOnly(
        EntryPoint = "expo_dotnet_windows_update_string_prop",
        CallConvs = new[] { typeof(CallConvCdecl) }
    )]
    public static int UpdateWindowsStringProp(
        nint runtimeContext,
        nint viewHandle,
        nint componentNameUtf8,
        int componentNameLength,
        nint propNameUtf8,
        int propNameLength,
        nint valueUtf8,
        int valueLength)
    {
        try
        {
            var context = RuntimeContextFromHandle(runtimeContext);
            var handle = GCHandle.FromIntPtr(viewHandle);
            if (handle.Target is null)
            {
                return -1;
            }

            LinkedExpoModulesProvider.UpdateViewProp(
                context,
                ReadUtf8(componentNameUtf8, componentNameLength),
                handle.Target,
                ReadUtf8(propNameUtf8, propNameLength),
                valueUtf8 == 0 ? null : ReadUtf8(valueUtf8, valueLength));
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex);
            return -1;
        }
    }

    private static DotnetRuntimeContext RuntimeContextFromHandle(nint runtimeContext)
    {
        if (runtimeContext == 0)
        {
            throw new ArgumentException("Runtime context handle is null.", nameof(runtimeContext));
        }

        var handle = GCHandle.FromIntPtr(runtimeContext);
        return handle.Target as DotnetRuntimeContext
            ?? throw new InvalidOperationException("Runtime context handle does not target DotnetRuntimeContext.");
    }

    private static unsafe string ReadUtf8(nint utf8, int length)
    {
        if (utf8 == 0 || length == 0)
        {
            return string.Empty;
        }

        return System.Text.Encoding.UTF8.GetString(new ReadOnlySpan<byte>((void*)utf8, length));
    }
`
      : '';

  return `${csharpBanner}
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Expo.JSI;
using Expo.ModulesCore;

namespace Expo.ModulesCore.Generated;

public static class EntryPoints
{
    [UnmanagedCallersOnly(
        EntryPoint = "expo_dotnet_create_runtime_context",
        CallConvs = new[] { typeof(CallConvCdecl) }
    )]
    public static nint CreateRuntimeContext(nint api, nint runtimeHandle)
    {
        try
        {
            return CreateRuntimeContextCore(api, runtimeHandle);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex);
            return 0;
        }
    }

    [UnmanagedCallersOnly(
        EntryPoint = "expo_dotnet_teardown_runtime_context",
        CallConvs = new[] { typeof(CallConvCdecl) }
    )]
    public static void TeardownRuntimeContext(nint runtimeContext)
    {
        TeardownRuntimeContextCore(runtimeContext);
    }

    private static nint CreateRuntimeContextCore(nint api, nint runtimeHandle)
    {
        var runtime = JavaScriptRuntime.FromNative(api, runtimeHandle);
        var context = new DotnetRuntimeContext(runtime);
        try
        {
            LinkedExpoModulesProvider.Register(context);
            return GCHandle.ToIntPtr(GCHandle.Alloc(context));
        }
        catch
        {
            context.Dispose();
            throw;
        }
    }

    private static void TeardownRuntimeContextCore(nint runtimeContext)
    {
        if (runtimeContext == 0)
        {
            return;
        }

        var handle = GCHandle.FromIntPtr(runtimeContext);
        if (handle.Target is DotnetRuntimeContext context)
        {
            context.Dispose();
        }

        handle.Free();
    }
${windowsViewEntryPoints}
}
`;
}

function relativePath(from: string, to: string): string {
  return path.relative(from, to).split(path.sep).join('/');
}

function escapeXmlAttribute(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
