require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('expo-modules-dotnet/package.json')"`), "scripts/autolinking.rb")
require 'pathname'

ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until
  File.exist?("#{ws_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb") ||
  ws_dir.expand_path.to_s == '/'
require "#{ws_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb"

ENV['RCT_NEW_ARCH_ENABLED'] = '1'
absolute_rn_macos_path = File.dirname(`node --print "require.resolve('react-native-macos/package.json')"`)
rn_macos_path = Pathname.new(absolute_rn_macos_path).relative_path_from(Pathname.pwd)

prepare_react_native_project!

target 'desktopapp-macOS' do
  platform :macos, '14.0'

  use_expo_modules!
  use_expo_modules_dotnet!(project_root: File.expand_path('..', __dir__))

  config_command = [
    'node',
    '--no-warnings',
    '--eval',
    'require("expo/bin/autolinking")',
    'expo-modules-autolinking',
    'react-native-config',
    '--json',
    '--platform',
    'ios'
  ]
  config = use_native_modules!(config_command)

  use_react_native!(
    :path => rn_macos_path.to_s,
    :hermes_enabled => true,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    installer.target_installation_results.pod_target_installation_results.each do |_pod_name, target_installation_result|
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['REACT_NATIVE_PATH'] = absolute_rn_macos_path
      end
    end

    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      next unless target.name == 'fmt'

      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end
  end
end
